// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ai

#ifndef _AI_UI_H
#define _AI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void start_anim_Animation(lv_obj_t * TargetObject, int delay);
void start_anim2_Animation(lv_obj_t * TargetObject, int delay);
void rec_task_Animation(lv_obj_t * TargetObject, int delay);
void text_pulse_Animation(lv_obj_t * TargetObject, int delay);
void gif_play_Animation(lv_obj_t * TargetObject, int delay);
void blink_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Page_Battery
void ui_Page_Battery_screen_init(void);
void ui_event_Page_Battery(lv_event_t * e);
extern lv_obj_t * ui_Page_Battery;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_Page_Start
void ui_Page_Start_screen_init(void);
void ui_event_Page_Start(lv_event_t * e);
extern lv_obj_t * ui_Page_Start;
extern lv_obj_t * ui_startlogo;
// SCREEN: ui_Page_loading
void ui_Page_loading_screen_init(void);
void ui_event_Page_loading(lv_event_t * e);
extern lv_obj_t * ui_Page_loading;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_loadpert;
// SCREEN: ui_Page_Vir
void ui_Page_Vir_screen_init(void);
void ui_event_Page_Vir(lv_event_t * e);
extern lv_obj_t * ui_Page_Vir;
extern lv_obj_t * ui_virp;
extern lv_obj_t * ui_virsmile;
void ui_event_virbtn1(lv_event_t * e);
extern lv_obj_t * ui_virbtn1;
extern lv_obj_t * ui_virtext1;
void ui_event_virbtn2(lv_event_t * e);
extern lv_obj_t * ui_virbtn2;
extern lv_obj_t * ui_virtext2;
// SCREEN: ui_Page_main
void ui_Page_main_screen_init(void);
void ui_event_Page_main(lv_event_t * e);
extern lv_obj_t * ui_Page_main;
extern lv_obj_t * ui_mainlist;
extern lv_obj_t * ui_mainlp1;
void ui_event_mainbtn1(lv_event_t * e);
extern lv_obj_t * ui_mainbtn1;
extern lv_obj_t * ui_mainlp2;
void ui_event_mainbtn2(lv_event_t * e);
extern lv_obj_t * ui_mainbtn2;
extern lv_obj_t * ui_mainlp3;
void ui_event_mainbtn3(lv_event_t * e);
extern lv_obj_t * ui_mainbtn3;
extern lv_obj_t * ui_mainlp4;
void ui_event_mainbtn4(lv_event_t * e);
extern lv_obj_t * ui_mainbtn4;
extern lv_obj_t * ui_maincontent;
extern lv_obj_t * ui_Devicep;
extern lv_obj_t * ui_maintime;
extern lv_obj_t * ui_mainwifi;
extern lv_obj_t * ui_mainb;
extern lv_obj_t * ui_btpert;
extern lv_obj_t * ui_mainble;
extern lv_obj_t * ui_maintitle;
extern lv_obj_t * ui_mcontrolp;
// SCREEN: ui_Page_Connect
void ui_Page_Connect_screen_init(void);
extern lv_obj_t * ui_Page_Connect;
extern lv_obj_t * ui_conn_arcl;
extern lv_obj_t * ui_conn_arcr;
extern lv_obj_t * ui_conn_panel1;
extern lv_obj_t * ui_connp11;
extern lv_obj_t * ui_connp12;
extern lv_obj_t * ui_connp13;
extern lv_obj_t * ui_connp14;
extern lv_obj_t * ui_conn_panel2;
extern lv_obj_t * ui_connp21;
extern lv_obj_t * ui_connp22;
extern lv_obj_t * ui_connp23;
extern lv_obj_t * ui_connp24;
extern lv_obj_t * ui_conn_QR;
void ui_event_conncancel(lv_event_t * e);
extern lv_obj_t * ui_conncancel;
void ui_event_connp1(lv_event_t * e);
extern lv_obj_t * ui_connp1;
void ui_event_arrow1(lv_event_t * e);
extern lv_obj_t * ui_arrow1;
void ui_event_connp2(lv_event_t * e);
extern lv_obj_t * ui_connp2;
void ui_event_arrow2(lv_event_t * e);
extern lv_obj_t * ui_arrow2;
// SCREEN: ui_Page_Wifi
void ui_Page_Wifi_screen_init(void);
extern lv_obj_t * ui_Page_Wifi;
extern lv_obj_t * ui_wifip1;
extern lv_obj_t * ui_wifiicon;
extern lv_obj_t * ui_wifissid;
extern lv_obj_t * ui_wifibtnt;
extern lv_obj_t * ui_wifip2;
extern lv_obj_t * ui_wifitext1;
extern lv_obj_t * ui_wifiimg;
extern lv_obj_t * ui_wifip3;
extern lv_obj_t * ui_wifitext3;
extern lv_obj_t * ui_wifilogo;
extern lv_obj_t * ui_wifitext2;
void ui_event_wificancel(lv_event_t * e);
extern lv_obj_t * ui_wificancel;
// SCREEN: ui_Page_CurTask1
void ui_Page_CurTask1_screen_init(void);
extern lv_obj_t * ui_Page_CurTask1;
extern lv_obj_t * ui_notasktext;
void ui_event_curtask1b(lv_event_t * e);
extern lv_obj_t * ui_curtask1b;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_Page_CurTask2
void ui_Page_CurTask2_screen_init(void);
extern lv_obj_t * ui_Page_CurTask2;
extern lv_obj_t * ui_waittext;
void ui_event_waitb(lv_event_t * e);
extern lv_obj_t * ui_waitb;
extern lv_obj_t * ui_waitarc;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_otap;
extern lv_obj_t * ui_otatper;
extern lv_obj_t * ui_otatsym;
// SCREEN: ui_Page_CurTask3
void ui_Page_CurTask3_screen_init(void);
extern lv_obj_t * ui_Page_CurTask3;
extern lv_obj_t * ui_revtext;
void ui_event_revb(lv_event_t * e);
extern lv_obj_t * ui_revb;
extern lv_obj_t * ui_Spinner3;
// SCREEN: ui_Page_ViewAva
void ui_Page_ViewAva_screen_init(void);
void ui_event_Page_ViewAva(lv_event_t * e);
extern lv_obj_t * ui_Page_ViewAva;
// SCREEN: ui_Page_ViewLive
void ui_Page_ViewLive_screen_init(void);
void ui_event_Page_ViewLive(lv_event_t * e);
extern lv_obj_t * ui_Page_ViewLive;
extern lv_obj_t * ui_viewlivp2;
extern lv_obj_t * ui_viewtext;
void ui_event_viewback(lv_event_t * e);
extern lv_obj_t * ui_viewback;
// SCREEN: ui_Page_LocTask
void ui_Page_LocTask_screen_init(void);
void ui_event_Page_LocTask(lv_event_t * e);
extern lv_obj_t * ui_Page_LocTask;
extern lv_obj_t * ui_menulist;
extern lv_obj_t * ui_custp1;
void ui_event_custbtn1(lv_event_t * e);
extern lv_obj_t * ui_custbtn1;
extern lv_obj_t * ui_custp2;
void ui_event_custbtn2(lv_event_t * e);
extern lv_obj_t * ui_custbtn2;
extern lv_obj_t * ui_custp3;
void ui_event_custbtn3(lv_event_t * e);
extern lv_obj_t * ui_custbtn3;
extern lv_obj_t * ui_menulp1;
void ui_event_menubtn1(lv_event_t * e);
extern lv_obj_t * ui_menubtn1;
extern lv_obj_t * ui_menulp2;
void ui_event_menubtn2(lv_event_t * e);
extern lv_obj_t * ui_menubtn2;
extern lv_obj_t * ui_menulp3;
void ui_event_menubtn3(lv_event_t * e);
extern lv_obj_t * ui_menubtn3;
extern lv_obj_t * ui_menulp4;
void ui_event_menubtn4(lv_event_t * e);
extern lv_obj_t * ui_menubtn4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_mimgp;
extern lv_obj_t * ui_lcontrolp;
// SCREEN: ui_Page_Set
void ui_Page_Set_screen_init(void);
void ui_event_Page_Set(lv_event_t * e);
extern lv_obj_t * ui_Page_Set;
extern lv_obj_t * ui_Set_panel;
void ui_event_setback(lv_event_t * e);
extern lv_obj_t * ui_setback;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_setbackt;
void ui_event_setapp(lv_event_t * e);
extern lv_obj_t * ui_setapp;
extern lv_obj_t * ui_setappt;
void ui_event_setwifi(lv_event_t * e);
extern lv_obj_t * ui_setwifi;
extern lv_obj_t * ui_setwifit;
void ui_event_setble(lv_event_t * e);
extern lv_obj_t * ui_setble;
extern lv_obj_t * ui_setblet;
extern lv_obj_t * ui_setblesw;
void ui_event_setvol(lv_event_t * e);
extern lv_obj_t * ui_setvol;
extern lv_obj_t * ui_setvolt;
void ui_event_setbri(lv_event_t * e);
extern lv_obj_t * ui_setbri;
extern lv_obj_t * ui_setbrit;
void ui_event_settime(lv_event_t * e);
extern lv_obj_t * ui_settime;
extern lv_obj_t * ui_settimt;
void ui_event_setrgb(lv_event_t * e);
extern lv_obj_t * ui_setrgb;
extern lv_obj_t * ui_setrgbt;
extern lv_obj_t * ui_setrgbsw;
void ui_event_setww(lv_event_t * e);
extern lv_obj_t * ui_setww;
extern lv_obj_t * ui_setwwt;
extern lv_obj_t * ui_setwwsw;
void ui_event_setdev(lv_event_t * e);
extern lv_obj_t * ui_setdev;
extern lv_obj_t * ui_setdevt;
void ui_event_setdown(lv_event_t * e);
extern lv_obj_t * ui_setdown;
extern lv_obj_t * ui_setdownt;
void ui_event_setfac(lv_event_t * e);
extern lv_obj_t * ui_setfac;
extern lv_obj_t * ui_setfact;
extern lv_obj_t * ui_settextp;
extern lv_obj_t * ui_Set_title;
extern lv_obj_t * ui_scontrolp;
// SCREEN: ui_Page_brivol
void ui_Page_brivol_screen_init(void);
extern lv_obj_t * ui_Page_brivol;
extern lv_obj_t * ui_bvpb;
extern lv_obj_t * ui_bvbimg;
extern lv_obj_t * ui_bvbt;
extern lv_obj_t * ui_bvbv;
extern lv_obj_t * ui_bvs;
extern lv_obj_t * ui_bvtp;
extern lv_obj_t * ui_bvtitle;
void ui_event_bvback(lv_event_t * e);
extern lv_obj_t * ui_bvback;
extern lv_obj_t * ui_vp;
void ui_event_vslider(lv_event_t * e);
extern lv_obj_t * ui_vslider;
extern lv_obj_t * ui_bp;
void ui_event_bslider(lv_event_t * e);
extern lv_obj_t * ui_bslider;
// SCREEN: ui_Page_SAbout
void ui_Page_SAbout_screen_init(void);
extern lv_obj_t * ui_Page_SAbout;
extern lv_obj_t * ui_AboutP;
void ui_event_aboutdn(lv_event_t * e);
extern lv_obj_t * ui_aboutdn;
extern lv_obj_t * ui_dnt1;
extern lv_obj_t * ui_dnt2;
void ui_event_aboutsv(lv_event_t * e);
extern lv_obj_t * ui_aboutsv;
extern lv_obj_t * ui_svt1;
extern lv_obj_t * ui_svt2;
void ui_event_aboutsn(lv_event_t * e);
extern lv_obj_t * ui_aboutsn;
extern lv_obj_t * ui_snt1;
extern lv_obj_t * ui_snt2;
void ui_event_abouteui(lv_event_t * e);
extern lv_obj_t * ui_abouteui;
extern lv_obj_t * ui_euit1;
extern lv_obj_t * ui_euit2;
void ui_event_aboutble(lv_event_t * e);
extern lv_obj_t * ui_aboutble;
extern lv_obj_t * ui_blet1;
extern lv_obj_t * ui_blet2;
void ui_event_aboutwifi(lv_event_t * e);
extern lv_obj_t * ui_aboutwifi;
extern lv_obj_t * ui_wifit1;
extern lv_obj_t * ui_wifit2;
void ui_event_Paboutb(lv_event_t * e);
extern lv_obj_t * ui_Paboutb;
extern lv_obj_t * ui_abtp;
extern lv_obj_t * ui_abtitle;
// SCREEN: ui_Page_Swipe
void ui_Page_Swipe_screen_init(void);
extern lv_obj_t * ui_Page_Swipe;
void ui_event_spsilder(lv_event_t * e);
extern lv_obj_t * ui_spsilder;
void ui_event_spback(lv_event_t * e);
extern lv_obj_t * ui_spback;
extern lv_obj_t * ui_sptext;
extern lv_obj_t * ui_swipep;
extern lv_obj_t * ui_sptitle;
extern lv_obj_t * ui_swipep2;
extern lv_obj_t * ui_sptext2;
// SCREEN: ui_Page_HA
void ui_Page_HA_screen_init(void);
void ui_event_Page_HA(lv_event_t * e);
extern lv_obj_t * ui_Page_HA;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Page_OTA
void ui_Page_OTA_screen_init(void);
extern lv_obj_t * ui_Page_OTA;
extern lv_obj_t * ui_otapanel;
extern lv_obj_t * ui_otatext;
extern lv_obj_t * ui_otaspinner;
extern lv_obj_t * ui_otaicon;
extern lv_obj_t * ui_otaarc;
void ui_event_otaback(lv_event_t * e);
extern lv_obj_t * ui_otaback;
// SCREEN: ui_Page_Slpt
void ui_Page_Slpt_screen_init(void);
extern lv_obj_t * ui_Page_Slpt;
extern lv_obj_t * ui_slptpanel;
void ui_event_slpt1(lv_event_t * e);
extern lv_obj_t * ui_slpt1;
void ui_event_slpt2(lv_event_t * e);
extern lv_obj_t * ui_slpt2;
void ui_event_slpt3(lv_event_t * e);
extern lv_obj_t * ui_slpt3;
void ui_event_slpt4(lv_event_t * e);
extern lv_obj_t * ui_slpt4;
void ui_event_slpt5(lv_event_t * e);
extern lv_obj_t * ui_slpt5;
void ui_event_slpt6(lv_event_t * e);
extern lv_obj_t * ui_slpt6;
void ui_event_slpt7(lv_event_t * e);
extern lv_obj_t * ui_slpt7;
void ui_event_slpback(lv_event_t * e);
extern lv_obj_t * ui_slpback;
// SCREEN: ui_Page_Wakup
void ui_Page_Wakup_screen_init(void);
extern lv_obj_t * ui_Page_Wakup;
extern lv_obj_t * ui_wakeuppanel;
extern lv_obj_t * ui_wakeupt1;
extern lv_obj_t * ui_wakeupt2;
extern lv_obj_t * ui_wakeupt3;
extern lv_obj_t * ui_wakeupt4;
// SCREEN: ui_Page_guide1
void ui_Page_guide1_screen_init(void);
void ui_event_Page_guide1(lv_event_t * e);
extern lv_obj_t * ui_Page_guide1;
void ui_event_guide1p1(lv_event_t * e);
extern lv_obj_t * ui_guide1p1;
extern lv_obj_t * ui_guide1img1;
extern lv_obj_t * ui_guide1t1;
void ui_event_guide1p2(lv_event_t * e);
extern lv_obj_t * ui_guide1p2;
extern lv_obj_t * ui_guide1img2;
extern lv_obj_t * ui_guide1t2;
void ui_event_guide1p3(lv_event_t * e);
extern lv_obj_t * ui_guide1p3;
void ui_event_guide1btn1(lv_event_t * e);
extern lv_obj_t * ui_guide1btn1;
extern lv_obj_t * ui_guide1btn1t;
void ui_event_guide1btn2(lv_event_t * e);
extern lv_obj_t * ui_guide1btn2;
extern lv_obj_t * ui_guide1btn2t;
void ui_event_guide1btn3(lv_event_t * e);
extern lv_obj_t * ui_guide1btn3;
// SCREEN: ui_Page_guide2
void ui_Page_guide2_screen_init(void);
void ui_event_Page_guide2(lv_event_t * e);
extern lv_obj_t * ui_Page_guide2;
void ui_event_guide2p1(lv_event_t * e);
extern lv_obj_t * ui_guide2p1;
extern lv_obj_t * ui_guide2t1;
void ui_event_guide2p2(lv_event_t * e);
extern lv_obj_t * ui_guide2p2;
extern lv_obj_t * ui_guide2img2;
extern lv_obj_t * ui_guide2t2;
// SCREEN: ui_Page_emoticon
void ui_Page_emoticon_screen_init(void);
extern lv_obj_t * ui_Page_emoticon;
extern lv_obj_t * ui_facet;
extern lv_obj_t * ui_facearc;
extern lv_obj_t * ui_faceper;
extern lv_obj_t * ui_facetper;
extern lv_obj_t * ui_facetsym;
// SCREEN: ui_Page_flag
void ui_Page_flag_screen_init(void);
extern lv_obj_t * ui_Page_flag;
extern lv_obj_t * ui_guideflagp;
void ui_event_guidebtn1(lv_event_t * e);
extern lv_obj_t * ui_guidebtn1;
extern lv_obj_t * ui_guidebtn1t;
void ui_event_guidebtn2(lv_event_t * e);
extern lv_obj_t * ui_guidebtn2;
extern lv_obj_t * ui_guidebtn2t;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_battery_warn_png);    // assets/battery_warn.png
LV_IMG_DECLARE(ui_img_logo_png);    // assets/logo.png
LV_IMG_DECLARE(ui_img_start_smile_png);    // assets/start_smile.png
LV_IMG_DECLARE(ui_img_page_main_png);    // assets/page_main.png
LV_IMG_DECLARE(ui_img_task_template_png);    // assets/Task Template.png
LV_IMG_DECLARE(ui_img_1415499115);    // assets/Task Template-.png
LV_IMG_DECLARE(ui_img_currenttask_png);    // assets/currenttask.png
LV_IMG_DECLARE(ui_img_1158392298);    // assets/currenttask-.png
LV_IMG_DECLARE(ui_img_extension_png);    // assets/extension.png
LV_IMG_DECLARE(ui_img_1722191473);    // assets/extension-2.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_setting_f_png);    // assets/setting_f.png
LV_IMG_DECLARE(ui_img_no_wifi_png);    // assets/no_wifi.png
LV_IMG_DECLARE(ui_img_battery_frame_png);    // assets/battery frame.png
LV_IMG_DECLARE(ui_img_ble_png);    // assets/ble.png
LV_IMG_DECLARE(ui_img_button_cancel_png);    // assets/button_cancel.png
LV_IMG_DECLARE(ui_img_arrow_png);    // assets/arrow.png
LV_IMG_DECLARE(ui_img_wifi_3_png);    // assets/wifi_3.png
LV_IMG_DECLARE(ui_img_1067503588);    // assets/wifi-Instructions.png
LV_IMG_DECLARE(ui_img_setback_png);    // assets/setback.png
LV_IMG_DECLARE(ui_img_template1_png);    // assets/template1.png
LV_IMG_DECLARE(ui_img_template1_f_png);    // assets/template1_f.png
LV_IMG_DECLARE(ui_img_template2_png);    // assets/template2.png
LV_IMG_DECLARE(ui_img_template2_f_png);    // assets/template2_f.png
LV_IMG_DECLARE(ui_img_template3_png);    // assets/template3.png
LV_IMG_DECLARE(ui_img_template3_f_png);    // assets/template3_f.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/Back.png
LV_IMG_DECLARE(ui_img_1195720223);    // assets/Back-2.png
LV_IMG_DECLARE(ui_img_human_png);    // assets/human.png
LV_IMG_DECLARE(ui_img_631814683);    // assets/human-2.png
LV_IMG_DECLARE(ui_img_578579305);    // assets/pet-2.png
LV_IMG_DECLARE(ui_img_pet_png);    // assets/pet.png
LV_IMG_DECLARE(ui_img_gesture_png);    // assets/gesture.png
LV_IMG_DECLARE(ui_img_30219097);    // assets/gesture-2.png
LV_IMG_DECLARE(ui_img_human_d_png);    // assets/human_d.png
LV_IMG_DECLARE(ui_img_volicon_png);    // assets/volicon.png
LV_IMG_DECLARE(ui_img_swipe_png);    // assets/swipe.png
LV_IMG_DECLARE(ui_img_wifiok_png);    // assets/wifiok.png
LV_IMG_DECLARE(ui_img_scroll_down_png);    // assets/scroll_down.png
LV_IMG_DECLARE(ui_img_scroll_up_png);    // assets/scroll_up.png
LV_IMG_DECLARE(ui_img_smile1_png);    // assets/smile1.png
LV_IMG_DECLARE(ui_img_wifi_0_png);    // assets/wifi_0.png
LV_IMG_DECLARE(ui_img_wifi_1_png);    // assets/wifi_1.png
LV_IMG_DECLARE(ui_img_wifi_2_png);    // assets/wifi_2.png
LV_IMG_DECLARE(ui_img_gradient_png);
LV_IMG_DECLARE(ui_img_brighticon_png);
LV_IMG_DECLARE(ui_img_gesture_d_png);
LV_IMG_DECLARE(ui_img_dog_d_png);
LV_IMG_DECLARE(ui_img_onboardclick_png);
LV_IMG_DECLARE(ui_img_error_png);
LV_IMG_DECLARE(ui_img_battery_charging_png);
LV_IMG_DECLARE(ui_img_wifi_abnormal_png);
LV_IMG_DECLARE(ui_img_backtomenu_png);


LV_FONT_DECLARE(ui_font_fbold16);
LV_FONT_DECLARE(ui_font_fbold24);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_fontbold26);
LV_FONT_DECLARE(ui_font_font_bold);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
