// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ai

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void slbattery_cb(lv_event_t * e);
void startload_cb(lv_event_t * e);
void loadsl_cb(lv_event_t * e);
void virtc_cb(lv_event_t * e);
void virtsl_cb(lv_event_t * e);
void virb1c_cb(lv_event_t * e);
void virb2c_cb(lv_event_t * e);
void mgesup_cb(lv_event_t * e);
void mgesdown_cb(lv_event_t * e);
void mclick_cb(lv_event_t * e);
void main1c_cb(lv_event_t * e);
void main1f_cb(lv_event_t * e);
void main2c_cb(lv_event_t * e);
void main2f_cb(lv_event_t * e);
void main3c_cb(lv_event_t * e);
void main3f_cb(lv_event_t * e);
void main4c_cb(lv_event_t * e);
void main4f_cb(lv_event_t * e);
void connc_cb(lv_event_t * e);
void arr1c_cb(lv_event_t * e);
void arr1f_cb(lv_event_t * e);
void arr2c_cb(lv_event_t * e);
void arr2f_cb(lv_event_t * e);
void ntaskb2c_cb(lv_event_t * e);
void waitbc_cb(lv_event_t * e);
void revbc_cb(lv_event_t * e);
void viewac_cb(lv_event_t * e);
void viewaf_cb(lv_event_t * e);
void viewasl_cb(lv_event_t * e);
void viewasul_cb(lv_event_t * e);
void ava1c_cb(lv_event_t * e);
void ava2c_cb(lv_event_t * e);
void avagc_cb(lv_event_t * e);
void viewlc_cb(lv_event_t * e);
void viewlf_cb(lv_event_t * e);
void viewlsl_cb(lv_event_t * e);
void viewlsul_cb(lv_event_t * e);
void liv1c_cb(lv_event_t * e);
void liv2c_cb(lv_event_t * e);
void vieback_cb(lv_event_t * e);
void livgc_cb(lv_event_t * e);
void lgesright_cb(lv_event_t * e);
void lgesleft_cb(lv_event_t * e);
void lclick_cb(lv_event_t * e);
void lunlds_cb(lv_event_t * e);
void lunlded_cb(lv_event_t * e);
void custb1c_cb(lv_event_t * e);
void custb1f_cb(lv_event_t * e);
void custb1df_cb(lv_event_t * e);
void custb2c_cb(lv_event_t * e);
void custb2f_cb(lv_event_t * e);
void custb2df_cb(lv_event_t * e);
void custb3c_cb(lv_event_t * e);
void custb3f_cb(lv_event_t * e);
void custb3df_cb(lv_event_t * e);
void loctask1c_cb(lv_event_t * e);
void loctask1f_cb(lv_event_t * e);
void loctask1df_cb(lv_event_t * e);
void loctask2c_cb(lv_event_t * e);
void loctask2f_cb(lv_event_t * e);
void loctask3c_cb(lv_event_t * e);
void loctask3f_cb(lv_event_t * e);
void loctask4c_cb(lv_event_t * e);
void loctask4f_cb(lv_event_t * e);
void sgesup_cb(lv_event_t * e);
void sgesdown_cb(lv_event_t * e);
void sclick_cb(lv_event_t * e);
void setbackf_cb(lv_event_t * e);
void setbackdf_cb(lv_event_t * e);
void setbackc_cb(lv_event_t * e);
void setappf_cb(lv_event_t * e);
void setappdf_cb(lv_event_t * e);
void setappc_cb(lv_event_t * e);
void setwific_cb(lv_event_t * e);
void setwifif_cb(lv_event_t * e);
void setwifidf_cb(lv_event_t * e);
void setblec_cb(lv_event_t * e);
void setblef_cb(lv_event_t * e);
void setbledf_cb(lv_event_t * e);
void setvolc_cb(lv_event_t * e);
void setvolf_cb(lv_event_t * e);
void setvoldf_cb(lv_event_t * e);
void setbric_cb(lv_event_t * e);
void setbrif_cb(lv_event_t * e);
void setbridf_cb(lv_event_t * e);
void settimec_cb(lv_event_t * e);
void settimef_cb(lv_event_t * e);
void settimedf_cb(lv_event_t * e);
void setrgbc_cb(lv_event_t * e);
void setrgbf_cb(lv_event_t * e);
void setrgbdf_cb(lv_event_t * e);
void setwwc_cb(lv_event_t * e);
void setwwf_cb(lv_event_t * e);
void setwwdf_cb(lv_event_t * e);
void setdevf_cb(lv_event_t * e);
void setdevdf_cb(lv_event_t * e);
void setdevc_cb(lv_event_t * e);
void setdownc_cb(lv_event_t * e);
void setdownf_cb(lv_event_t * e);
void setdowndf_cb(lv_event_t * e);
void setfac_cb(lv_event_t * e);
void setfacf_cb(lv_event_t * e);
void setfacdf_cb(lv_event_t * e);
void preset_cb(lv_event_t * e);
void volvc_cb(lv_event_t * e);
void volre_cb(lv_event_t * e);
void brivc_cb(lv_event_t * e);
void brire_cb(lv_event_t * e);
void abdnf_cb(lv_event_t * e);
void abdndf_cb(lv_event_t * e);
void absvf_cb(lv_event_t * e);
void absvdf_cb(lv_event_t * e);
void absnf_cb(lv_event_t * e);
void absndf_cb(lv_event_t * e);
void abeuif_cb(lv_event_t * e);
void abeuidf_cb(lv_event_t * e);
void abblef_cb(lv_event_t * e);
void abbledf_cb(lv_event_t * e);
void paboutc_cb(lv_event_t * e);
void slidervc_cb(lv_event_t * e);
void sliderr_cb(lv_event_t * e);
void hap_cb(lv_event_t * e);
void slpt1c_cb(lv_event_t * e);
void slpt2c_cb(lv_event_t * e);
void slpt3c_cb(lv_event_t * e);
void slpt4c_cb(lv_event_t * e);
void slpt5c_cb(lv_event_t * e);
void slpt6c_cb(lv_event_t * e);
void slpt7c_cb(lv_event_t * e);

void waitForWifi();
void waitForBinding();
void waitForAddDev();
void bindFinish();
void wifiConnectFailed();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
