// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#ifndef _UI_COMP_MENUCOMPONENT_H
#define _UI_COMP_MENUCOMPONENT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT menucomponent
#define UI_COMP_MENUCOMPONENT_MENUCOMPONENT 0
#define UI_COMP_MENUCOMPONENT_MENULIST 1
#define UI_COMP_MENUCOMPONENT_MENULIST_MENUBTN1 2
#define UI_COMP_MENUCOMPONENT_MENULIST_MENUBTN2 3
#define UI_COMP_MENUCOMPONENT_MENULIST_MENUBTN3 4
#define UI_COMP_MENUCOMPONENT_MENUPANEL 5
#define UI_COMP_MENUCOMPONENT_MENUPANEL_MENUCONTENT 6
#define UI_COMP_MENUCOMPONENT_MENUPANEL_MENUCONTENT_MENUTEXT 7
#define _UI_COMP_MENUCOMPONENT_NUM 8
lv_obj_t * ui_menucomponent_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
