// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai

#include "../ui.h"

void ui_atask_down_screen_init(void)
{
    ui_atask_down = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_atask_down, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_atask_down, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_atask_down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ataskd_text = lv_label_create(ui_atask_down);
    lv_obj_set_width(ui_ataskd_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ataskd_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ataskd_text, 0);
    lv_obj_set_y(ui_ataskd_text, -20);
    lv_obj_set_align(ui_ataskd_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ataskd_text, "Receiving task\n     from app");
    lv_obj_set_style_text_color(ui_ataskd_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ataskd_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ataskd_text, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_atask_arc2 = lv_arc_create(ui_atask_down);
    lv_obj_set_width(ui_atask_arc2, 240);
    lv_obj_set_height(ui_atask_arc2, 240);
    lv_obj_set_align(ui_atask_arc2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_atask_arc2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_value(ui_atask_arc2, 50);
    lv_arc_set_bg_angles(ui_atask_arc2, 0, 360);
    lv_arc_set_rotation(ui_atask_arc2, 270);
    lv_obj_set_style_arc_width(ui_atask_arc2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_atask_arc2, lv_color_hex(0x62B442), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_atask_arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_atask_arc2, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_atask_arc2, lv_color_hex(0x62B442), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_atask_arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_atask_sec3 = lv_label_create(ui_atask_down);
    lv_obj_set_width(ui_atask_sec3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_atask_sec3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_atask_sec3, -130);
    lv_obj_set_y(ui_atask_sec3, 45);
    lv_obj_set_align(ui_atask_sec3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_atask_sec3, "3");
    lv_obj_set_style_text_color(ui_atask_sec3, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_atask_sec3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_atask_sec3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_atask_sec2 = lv_label_create(ui_atask_down);
    lv_obj_set_width(ui_atask_sec2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_atask_sec2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_atask_sec2, -130);
    lv_obj_set_y(ui_atask_sec2, 45);
    lv_obj_set_align(ui_atask_sec2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_atask_sec2, "2");
    lv_obj_set_style_text_color(ui_atask_sec2, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_atask_sec2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_atask_sec2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_atask_sec1 = lv_label_create(ui_atask_down);
    lv_obj_set_width(ui_atask_sec1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_atask_sec1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_atask_sec1, -130);
    lv_obj_set_y(ui_atask_sec1, 45);
    lv_obj_set_align(ui_atask_sec1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_atask_sec1, "1");
    lv_obj_set_style_text_color(ui_atask_sec1, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_atask_sec1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_atask_sec1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_atask_press = lv_label_create(ui_atask_down);
    lv_obj_set_width(ui_atask_press, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_atask_press, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_atask_press, -180);
    lv_obj_set_y(ui_atask_press, 30);
    lv_obj_set_align(ui_atask_press, LV_ALIGN_CENTER);
    lv_label_set_text(ui_atask_press, "Click to continue");
    lv_obj_set_style_text_color(ui_atask_press, lv_color_hex(0x002FA7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_atask_press, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_atask_down, ui_event_atask_down, LV_EVENT_ALL, NULL);

}
