// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai

#include "../ui.h"

void ui_ltask_back_screen_init(void)
{
    ui_ltask_back = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ltask_back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ltaskbb1 = lv_btn_create(ui_ltask_back);
    lv_obj_set_width(ui_ltaskbb1, 120);
    lv_obj_set_height(ui_ltaskbb1, 40);
    lv_obj_set_x(ui_ltaskbb1, 0);
    lv_obj_set_y(ui_ltaskbb1, 30);
    lv_obj_set_align(ui_ltaskbb1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ltaskbb1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ltaskbb1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ltaskbb1, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ltaskbb1, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ltaskbb1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ltaskbb1t = lv_label_create(ui_ltaskbb1);
    lv_obj_set_width(ui_ltaskbb1t, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ltaskbb1t, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ltaskbb1t, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ltaskbb1t, "End Task");

    ui_ltaskbb2 = lv_btn_create(ui_ltask_back);
    lv_obj_set_width(ui_ltaskbb2, 32);
    lv_obj_set_height(ui_ltaskbb2, 32);
    lv_obj_set_x(ui_ltaskbb2, 0);
    lv_obj_set_y(ui_ltaskbb2, 92);
    lv_obj_set_align(ui_ltaskbb2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ltaskbb2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ltaskbb2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ltaskbb2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ltaskbb2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ltaskbb2, &ui_img_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ltaskbb2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ltaskbb2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ltaskbb1, ui_event_ltaskbb1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ltaskbb2, ui_event_ltaskbb2, LV_EVENT_ALL, NULL);

}
