// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai

#include "../ui.h"

static void menu_scroll_cb(lv_event_t* e) {
    lv_obj_t* cont = lv_event_get_target(e);

    lv_area_t cont_a;
    lv_obj_get_coords(cont, &cont_a);
    int32_t cont_y_center = lv_area_get_height(&cont_a) / 2;
    // ESP_LOGI(TAG, "cont_y_center: %d", cont_y_center);

    // int32_t r = lv_obj_get_height(cont);
    int32_t r = 140;
    uint32_t i;
    uint32_t child_cnt = lv_obj_get_child_cnt(cont);

    for(i = 0; i < child_cnt; i++) {
        lv_obj_t * child = lv_obj_get_child(cont, i);
        lv_area_t child_a;
        lv_obj_get_coords(child, &child_a);

        int32_t child_y_center = child_a.y1 + lv_area_get_height(&child_a) / 2;

        int32_t diff_y = child_y_center - cont_y_center;
        diff_y = LV_ABS(diff_y);

        /*Get the x of diff_y on a circle.*/
        int32_t x;
        /*If diff_y is out of the circle use the last point of the circle (the radius)*/
        if(diff_y >= r) {
            x = r;
        }
        else {
            /*Use Pythagoras theorem to get x from radius and y*/
            uint32_t x_sqr = r * r - diff_y * diff_y;
            lv_sqrt_res_t res;
            lv_sqrt(x_sqr, &res, 0x8000);   /*Use lvgl's built in sqrt root function*/
            x = r - res.i;
        }
        /*Translate the item by the calculated X coordinate*/
        lv_obj_set_style_translate_x(child, x, 0);
        // lv_obj_set_height(child, 30 - x/2);
        // lv_obj_set_width(child, 30 - x/2);
    }
}

void ui_ltaskscreen_screen_init(void)
{
    ui_ltaskscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ltaskscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menupanel = lv_obj_create(ui_ltaskscreen);
    lv_obj_set_width(ui_menupanel, 400);
    lv_obj_set_height(ui_menupanel, 400);
    lv_obj_set_align(ui_menupanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menupanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menulist = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_menulist, 100);
    lv_obj_set_height(ui_menulist, 240);
    lv_obj_set_x(ui_menulist, 60);
    lv_obj_set_y(ui_menulist, 0);
    lv_obj_set_align(ui_menulist, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_menulist, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_menulist, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_menulist, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_style_bg_color(ui_menulist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menulist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_menulist, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_menulist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menulp1 = lv_obj_create(ui_menulist);
    lv_obj_set_width(ui_menulp1, 30);
    lv_obj_set_height(ui_menulp1, 30);
    lv_obj_set_align(ui_menulp1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menulp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menulp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menulp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menulp1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menulp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menubtn1 = lv_btn_create(ui_menulp1);
    lv_obj_set_height(ui_menubtn1, 30);
    lv_obj_set_width(ui_menubtn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_menubtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menubtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menubtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menubtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn1, &ui_img_human1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_menubtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menubtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_menubtn1, &ui_img_human2_png, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_menubtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_menulp2 = lv_obj_create(ui_menulist);
    lv_obj_set_width(ui_menulp2, 30);
    lv_obj_set_height(ui_menulp2, 30);
    lv_obj_set_align(ui_menulp2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menulp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menulp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menulp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menulp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menulp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menubtn2 = lv_btn_create(ui_menulp2);
    lv_obj_set_height(ui_menubtn2, 30);
    lv_obj_set_width(ui_menubtn2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_menubtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menubtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menubtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menubtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menubtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn2, &ui_img_apple1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_menubtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_menubtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn2, &ui_img_apple2_png, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_menulp3 = lv_obj_create(ui_menulist);
    lv_obj_set_width(ui_menulp3, 30);
    lv_obj_set_height(ui_menulp3, 30);
    lv_obj_set_align(ui_menulp3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menulp3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menulp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menulp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menulp3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menulp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menubtn3 = lv_btn_create(ui_menulp3);
    lv_obj_set_height(ui_menubtn3, 30);
    lv_obj_set_width(ui_menubtn3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_menubtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menubtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menubtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menubtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn3, &ui_img_gesture1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_menubtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menubtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_menubtn3, &ui_img_gesture2_png, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_menubtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_menulp4 = lv_obj_create(ui_menulist);
    lv_obj_set_width(ui_menulp4, 30);
    lv_obj_set_height(ui_menulp4, 30);
    lv_obj_set_align(ui_menulp4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menulp4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menulp4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menulp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menulp4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menulp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menubtn4 = lv_btn_create(ui_menulp4);
    lv_obj_set_height(ui_menubtn4, 30);
    lv_obj_set_width(ui_menubtn4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_menubtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menubtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menubtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menubtn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menubtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn4, &ui_img_back1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_menubtn4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_menubtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn4, &ui_img_back2_png, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_menucircle = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_menucircle, 300);
    lv_obj_set_height(ui_menucircle, 300);
    lv_obj_set_x(ui_menucircle, 110);
    lv_obj_set_y(ui_menucircle, 0);
    lv_obj_set_align(ui_menucircle, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_menucircle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menucircle, 130, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menucontent = lv_obj_create(ui_menucircle);
    lv_obj_set_width(ui_menucontent, 171);
    lv_obj_set_height(ui_menucontent, 224);
    lv_obj_set_x(ui_menucontent, 5);
    lv_obj_set_y(ui_menucontent, 0);
    lv_obj_set_align(ui_menucontent, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_menucontent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menucontent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menucontent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menucontent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menucontent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_menubtn1, ui_event_menubtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menubtn2, ui_event_menubtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menubtn3, ui_event_menubtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menubtn4, ui_event_menubtn4, LV_EVENT_ALL, NULL);

    lv_obj_set_scroll_snap_y(ui_menulist, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_dir(ui_menulist, LV_DIR_VER);

    lv_obj_add_event_cb(ui_menulist, menu_scroll_cb, LV_EVENT_SCROLL, NULL);
    lv_obj_scroll_to_view(lv_obj_get_child(ui_menulist, 0), LV_ANIM_OFF);
    lv_event_send(ui_menulist, LV_EVENT_SCROLL, NULL);

}
