// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai

#include "../ui.h"

static void main_scroll_cb(lv_event_t* e) {
    lv_obj_t* cont = lv_event_get_target(e);

    lv_area_t cont_a;
    lv_obj_get_coords(cont, &cont_a);
    int32_t cont_y_center = lv_area_get_height(&cont_a) / 2;
    // ESP_LOGI(TAG, "cont_y_center: %d", cont_y_center);

    // int32_t r = lv_obj_get_height(cont);
    int32_t r = 140;
    uint32_t i;
    uint32_t child_cnt = lv_obj_get_child_cnt(cont);

    for(i = 0; i < child_cnt; i++) {
        lv_obj_t * child = lv_obj_get_child(cont, i);
        lv_area_t child_a;
        lv_obj_get_coords(child, &child_a);

        int32_t child_y_center = child_a.y1 + lv_area_get_height(&child_a) / 2;

        int32_t diff_y = child_y_center - cont_y_center;
        diff_y = LV_ABS(diff_y);

        /*Get the x of diff_y on a circle.*/
        int32_t x;
        /*If diff_y is out of the circle use the last point of the circle (the radius)*/
        if(diff_y >= r) {
            x = r;
        }
        else {
            /*Use Pythagoras theorem to get x from radius and y*/
            uint32_t x_sqr = r * r - diff_y * diff_y;
            lv_sqrt_res_t res;
            lv_sqrt(x_sqr, &res, 0x8000);   /*Use lvgl's built in sqrt root function*/
            x = r - res.i;
        }
        /*Translate the item by the calculated X coordinate*/
        lv_obj_set_style_translate_x(child, x, 0);
        // lv_obj_set_height(child, 30 - x/2);
        // lv_obj_set_width(child, 30 - x/2);
    }
}

void ui_mainscreen_screen_init(void)
{
    ui_mainscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainpanel = lv_obj_create(ui_mainscreen);
    lv_obj_set_width(ui_mainpanel, 400);
    lv_obj_set_height(ui_mainpanel, 400);
    lv_obj_set_align(ui_mainpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainlist = lv_obj_create(ui_mainpanel);
    lv_obj_set_width(ui_mainlist, 100);
    lv_obj_set_height(ui_mainlist, 240);
    lv_obj_set_x(ui_mainlist, 60);
    lv_obj_set_y(ui_mainlist, 0);
    lv_obj_set_align(ui_mainlist, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_mainlist, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_mainlist, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_mainlist, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_mainlist, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_mainlist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainlist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainlist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainlist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_mainlist, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_mainlist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainlp1 = lv_obj_create(ui_mainlist);
    lv_obj_set_width(ui_mainlp1, 30);
    lv_obj_set_height(ui_mainlp1, 30);
    lv_obj_set_align(ui_mainlp1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainlp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainlp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainlp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainlp1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainlp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainbtn1 = lv_btn_create(ui_mainlp1);
    lv_obj_set_height(ui_mainbtn1, 30);
    lv_obj_set_width(ui_mainbtn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_mainbtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainbtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mainbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainbtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_mainbtn1, &ui_img_onboard_demo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mainbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mainbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainbtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_mainbtn1, &ui_img_19533631, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_mainbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_mainbtn1, 0, LV_STATE_FOCUS_KEY);

    ui_mainlp2 = lv_obj_create(ui_mainlist);
    lv_obj_set_width(ui_mainlp2, 30);
    lv_obj_set_height(ui_mainlp2, 30);
    lv_obj_set_align(ui_mainlp2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainlp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainlp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainlp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainlp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainlp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainbtn2 = lv_btn_create(ui_mainlp2);
    lv_obj_set_height(ui_mainbtn2, 30);
    lv_obj_set_width(ui_mainbtn2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_mainbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mainbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainbtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_mainbtn2, &ui_img_current_task_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mainbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mainbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainbtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_mainbtn2, &ui_img_1721754357, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_mainbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_mainbtn2, 0, LV_STATE_FOCUS_KEY);

    ui_mainlp3 = lv_obj_create(ui_mainlist);
    lv_obj_set_width(ui_mainlp3, 30);
    lv_obj_set_height(ui_mainlp3, 30);
    lv_obj_set_align(ui_mainlp3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainlp3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainlp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainlp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainlp3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainlp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainbtn3 = lv_btn_create(ui_mainlp3);
    lv_obj_set_height(ui_mainbtn3, 30);
    lv_obj_set_width(ui_mainbtn3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_mainbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainbtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mainbtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainbtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_mainbtn3, &ui_img_2022210068, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mainbtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainbtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_mainbtn3, &ui_img_ha_png, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_mainbtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_mainbtn3, 0, LV_STATE_FOCUS_KEY);

    ui_mainlp4 = lv_obj_create(ui_mainlist);
    lv_obj_set_width(ui_mainlp4, 30);
    lv_obj_set_height(ui_mainlp4, 30);
    lv_obj_set_align(ui_mainlp4, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_mainlp4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainlp4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainlp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainlp4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainlp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainbtn4 = lv_btn_create(ui_mainlp4);
    lv_obj_set_height(ui_mainbtn4, 30);
    lv_obj_set_width(ui_mainbtn4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_mainbtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainbtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mainbtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainbtn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_mainbtn4, &ui_img_setting_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mainbtn4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainbtn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_mainbtn4, &ui_img_457376777, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_mainbtn4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_mainbtn4, 0, LV_STATE_FOCUS_KEY);

    ui_maincircle = lv_obj_create(ui_mainpanel);
    lv_obj_set_width(ui_maincircle, 300);
    lv_obj_set_height(ui_maincircle, 300);
    lv_obj_set_x(ui_maincircle, 110);
    lv_obj_set_y(ui_maincircle, 0);
    lv_obj_set_align(ui_maincircle, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_maincircle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_maincircle, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_maincircle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_maincircle, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_maincircle, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_maincircle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_maincircle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_maincircle, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_src(ui_maincircle, &ui_img_onboarddemobackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_maincircle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_maincircle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maincontent = lv_obj_create(ui_maincircle);
    lv_obj_set_width(ui_maincontent, 171);
    lv_obj_set_height(ui_maincontent, 234);
    lv_obj_set_x(ui_maincontent, 5);
    lv_obj_set_y(ui_maincontent, 0);
    lv_obj_set_align(ui_maincontent, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_maincontent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_maincontent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_maincontent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_maincontent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_maincontent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maintitle = lv_label_create(ui_maincontent);
    lv_obj_set_width(ui_maintitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maintitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maintitle, -3);
    lv_obj_set_y(ui_maintitle, -1);
    lv_obj_set_align(ui_maintitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maintitle, "Onboard Demo");
    lv_obj_set_style_text_color(ui_maintitle, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maintitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maintitle, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maintime = lv_label_create(ui_maincontent);
    lv_obj_set_width(ui_maintime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maintime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maintime, -12);
    lv_obj_set_y(ui_maintime, 90);
    lv_obj_set_align(ui_maintime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maintime, "18:20");
    lv_obj_set_style_text_color(ui_maintime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maintime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainwifi = lv_img_create(ui_maincontent);
    lv_img_set_src(ui_mainwifi, &ui_img_wifi_4_png);
    lv_obj_set_width(ui_mainwifi, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_mainwifi, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_mainwifi, -16);
    lv_obj_set_y(ui_mainwifi, 65);
    lv_obj_set_align(ui_mainwifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainwifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_mainwifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_mainwifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainby = lv_img_create(ui_maincontent);
    lv_img_set_src(ui_mainby, &ui_img_battery_5_png);
    lv_obj_set_width(ui_mainby, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_mainby, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_mainby, 66);
    lv_obj_set_y(ui_mainby, 65);
    lv_obj_set_align(ui_mainby, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_mainby, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainby, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_mainby, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_mainby, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mainbtn1, ui_event_mainbtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainbtn2, ui_event_mainbtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainbtn3, ui_event_mainbtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainbtn4, ui_event_mainbtn4, LV_EVENT_ALL, NULL);

    lv_obj_set_scroll_snap_y(ui_mainlist, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_dir(ui_mainlist, LV_DIR_VER);

    lv_obj_add_event_cb(ui_mainlist, main_scroll_cb, LV_EVENT_SCROLL, NULL);
    lv_obj_scroll_to_view(lv_obj_get_child(ui_mainlist, 0), LV_ANIM_OFF);
    lv_event_send(ui_mainlist, LV_EVENT_SCROLL, NULL);


}
