// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai

#include "../ui.h"

void ui_nocurrentT_screen_init(void)
{
    ui_nocurrentT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_nocurrentT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_notasktext = lv_label_create(ui_nocurrentT);
    lv_obj_set_width(ui_notasktext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_notasktext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_notasktext, 0);
    lv_obj_set_y(ui_notasktext, -10);
    lv_obj_set_align(ui_notasktext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_notasktext, "No current\n  task yet");
    lv_obj_set_style_text_font(ui_notasktext, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notaskbtn = lv_btn_create(ui_nocurrentT);
    lv_obj_set_width(ui_notaskbtn, 140);
    lv_obj_set_height(ui_notaskbtn, 40);
    lv_obj_set_x(ui_notaskbtn, 0);
    lv_obj_set_y(ui_notaskbtn, 65);
    lv_obj_set_align(ui_notaskbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_notaskbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_notaskbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_notaskbtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_notaskbtn, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_notaskbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notasklabel = lv_label_create(ui_notaskbtn);
    lv_obj_set_width(ui_notasklabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_notasklabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_notasklabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_notasklabel, "Create New Task");

    lv_obj_add_event_cb(ui_notaskbtn, ui_event_notaskbtn, LV_EVENT_ALL, NULL);

}
