// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai

#include "../ui.h"

void ui_Page_CurTask2_screen_init(void)
{
    ui_Page_CurTask2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_CurTask2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_CurTask2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_CurTask2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waittext = lv_label_create(ui_Page_CurTask2);
    lv_obj_set_width(ui_waittext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waittext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_waittext, 0);
    lv_obj_set_y(ui_waittext, 7);
    lv_obj_set_align(ui_waittext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waittext, "waiting for \n  task from\n       app");
    lv_obj_set_style_text_color(ui_waittext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waittext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_waittext, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waitspinner = lv_spinner_create(ui_Page_CurTask2, 1000, 90);
    lv_obj_set_width(ui_waitspinner, 40);
    lv_obj_set_height(ui_waitspinner, 40);
    lv_obj_set_x(ui_waitspinner, 0);
    lv_obj_set_y(ui_waitspinner, -90);
    lv_obj_set_align(ui_waitspinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_waitspinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_waitspinner, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_waitspinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_waitspinner, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_waitspinner, lv_color_hex(0x91BF25), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_waitspinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_waitspinner, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_waitb = lv_btn_create(ui_Page_CurTask2);
    lv_obj_set_width(ui_waitb, 60);
    lv_obj_set_height(ui_waitb, 60);
    lv_obj_set_x(ui_waitb, 0);
    lv_obj_set_y(ui_waitb, 120);
    lv_obj_set_align(ui_waitb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_waitb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_waitb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_waitb, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_waitb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_waitb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_waitb, &ui_img_button_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_waitb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_waitb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_waitb, ui_event_waitb, LV_EVENT_ALL, NULL);

}
