// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai

#include "../ui.h"

void ui_Page_Connect_screen_init(void)
{
    ui_Page_Connect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Connect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conn_arcl = lv_arc_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_arcl, 410);
    lv_obj_set_height(ui_conn_arcl, 410);
    lv_obj_set_align(ui_conn_arcl, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_conn_arcl, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_conn_arcl, 100);
    lv_arc_set_bg_angles(ui_conn_arcl, 95, 265);
    lv_obj_set_style_arc_color(ui_conn_arcl, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_conn_arcl, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_conn_arcl, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_conn_arcl, lv_color_hex(0xA9DE2C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_conn_arcl, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_conn_arcl, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_conn_arcl, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_arcl, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_conn_arcl, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_conn_arcl, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_conn_arcr = lv_arc_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_arcr, 410);
    lv_obj_set_height(ui_conn_arcr, 410);
    lv_obj_set_align(ui_conn_arcr, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_conn_arcr, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_conn_arcr, 100);
    lv_arc_set_bg_angles(ui_conn_arcr, 95, 265);
    lv_arc_set_rotation(ui_conn_arcr, 180);
    lv_obj_set_style_arc_color(ui_conn_arcr, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_conn_arcr, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_conn_arcr, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_conn_arcr, lv_color_hex(0xA9DE2C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_conn_arcr, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_conn_arcr, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_conn_arcr, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_arcr, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_conn_panel1 = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_panel1, 185);
    lv_obj_set_height(ui_conn_panel1, 82);
    lv_obj_set_x(ui_conn_panel1, 0);
    lv_obj_set_y(ui_conn_panel1, -110);
    lv_obj_set_align(ui_conn_panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_conn_panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_conn_panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_conn_panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_conn_panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp11 = lv_label_create(ui_conn_panel1);
    lv_obj_set_width(ui_connp11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp11, -30);
    lv_obj_set_y(ui_connp11, 0);
    lv_obj_set_align(ui_connp11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp11, "Mate");
    lv_obj_set_style_text_color(ui_connp11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp12 = lv_label_create(ui_conn_panel1);
    lv_obj_set_width(ui_connp12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp12, 93);
    lv_obj_set_y(ui_connp12, 0);
    lv_obj_set_align(ui_connp12, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_connp12, "(   / 2)");
    lv_obj_set_style_text_color(ui_connp12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp13 = lv_label_create(ui_conn_panel1);
    lv_obj_set_width(ui_connp13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp13, 0);
    lv_obj_set_y(ui_connp13, -30);
    lv_obj_set_align(ui_connp13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp13, "Get SenseCAP");
    lv_obj_set_style_text_color(ui_connp13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp13, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp14 = lv_label_create(ui_conn_panel1);
    lv_obj_set_width(ui_connp14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp14, 35);
    lv_obj_set_y(ui_connp14, 0);
    lv_obj_set_align(ui_connp14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp14, "1");
    lv_obj_set_style_text_color(ui_connp14, lv_color_hex(0xA9DE2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp14, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conn_panel2 = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_panel2, 185);
    lv_obj_set_height(ui_conn_panel2, 85);
    lv_obj_set_x(ui_conn_panel2, 0);
    lv_obj_set_y(ui_conn_panel2, -110);
    lv_obj_set_align(ui_conn_panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conn_panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conn_panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_conn_panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_conn_panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_conn_panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp21 = lv_label_create(ui_conn_panel2);
    lv_obj_set_width(ui_connp21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp21, -17);
    lv_obj_set_y(ui_connp21, 0);
    lv_obj_set_align(ui_connp21, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_connp21, "Bluetooth");
    lv_obj_set_style_text_color(ui_connp21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp21, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp22 = lv_label_create(ui_conn_panel2);
    lv_obj_set_width(ui_connp22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp22, 98);
    lv_obj_set_y(ui_connp22, 0);
    lv_obj_set_align(ui_connp22, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_connp22, "(    / 2)");
    lv_obj_set_style_text_color(ui_connp22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp22, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp23 = lv_label_create(ui_conn_panel2);
    lv_obj_set_width(ui_connp23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp23, 0);
    lv_obj_set_y(ui_connp23, -30);
    lv_obj_set_align(ui_connp23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp23, "Connect");
    lv_obj_set_style_text_color(ui_connp23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp23, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp24 = lv_label_create(ui_conn_panel2);
    lv_obj_set_width(ui_connp24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp24, 40);
    lv_obj_set_y(ui_connp24, 0);
    lv_obj_set_align(ui_connp24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp24, "2");
    lv_obj_set_style_text_color(ui_connp24, lv_color_hex(0xA9DE2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp24, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conn_QR = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_QR, 160);
    lv_obj_set_height(ui_conn_QR, 160);
    lv_obj_set_align(ui_conn_QR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_conn_QR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_conn_spinner = lv_spinner_create(ui_Page_Connect, 1000, 90);
    lv_obj_set_width(ui_conn_spinner, 40);
    lv_obj_set_height(ui_conn_spinner, 40);
    lv_obj_set_x(ui_conn_spinner, 0);
    lv_obj_set_y(ui_conn_spinner, -50);
    lv_obj_set_align(ui_conn_spinner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conn_spinner, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conn_spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_conn_spinner, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_conn_spinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_conn_spinner, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_conn_spinner, lv_color_hex(0x91BF25), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_conn_spinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_conn_spinner, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_conn_panel3 = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_panel3, 160);
    lv_obj_set_height(ui_conn_panel3, 109);
    lv_obj_set_x(ui_conn_panel3, -1);
    lv_obj_set_y(ui_conn_panel3, 43);
    lv_obj_set_align(ui_conn_panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_conn_panel3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_conn_panel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_conn_panel3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conn_panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_conn_panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_conn_panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_conn_panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp31 = lv_label_create(ui_conn_panel3);
    lv_obj_set_width(ui_connp31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_connp31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp31, "Loading");
    lv_obj_set_style_text_color(ui_connp31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp31, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp32 = lv_label_create(ui_conn_panel3);
    lv_obj_set_width(ui_connp32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp32, 0);
    lv_obj_set_y(ui_connp32, 55);
    lv_obj_set_align(ui_connp32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp32, "waiting for \nconnection");
    lv_obj_set_style_text_color(ui_connp32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp32, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp32, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conn_panel4 = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_panel4, 213);
    lv_obj_set_height(ui_conn_panel4, 126);
    lv_obj_set_x(ui_conn_panel4, -1);
    lv_obj_set_y(ui_conn_panel4, 43);
    lv_obj_set_align(ui_conn_panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_conn_panel4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_conn_panel4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_conn_panel4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conn_panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_conn_panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_conn_panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_conn_panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp41 = lv_label_create(ui_conn_panel4);
    lv_obj_set_width(ui_connp41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_connp41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp41, "ble Connect\nSuccessfully");
    lv_obj_set_style_text_color(ui_connp41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp41, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp42 = lv_label_create(ui_conn_panel4);
    lv_obj_set_width(ui_connp42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp42, 0);
    lv_obj_set_y(ui_connp42, 55);
    lv_obj_set_align(ui_connp42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp42, "waiting for Wifi");
    lv_obj_set_style_text_color(ui_connp42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp42, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp42, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conn_panel5 = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_panel5, 193);
    lv_obj_set_height(ui_conn_panel5, 142);
    lv_obj_set_x(ui_conn_panel5, -1);
    lv_obj_set_y(ui_conn_panel5, 43);
    lv_obj_set_align(ui_conn_panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_conn_panel5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_conn_panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_conn_panel5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conn_panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_conn_panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_conn_panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_conn_panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp52 = lv_label_create(ui_conn_panel5);
    lv_obj_set_width(ui_connp52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp52, 0);
    lv_obj_set_y(ui_connp52, 55);
    lv_obj_set_align(ui_connp52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp52, "ble Connect\nSuccessfully");
    lv_obj_set_style_text_color(ui_connp52, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp52, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp52, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp51 = lv_label_create(ui_conn_panel5);
    lv_obj_set_width(ui_connp51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_connp51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp51, "waiting for\n       wifi");
    lv_obj_set_style_text_color(ui_connp51, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp51, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conn_panel6 = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_panel6, 160);
    lv_obj_set_height(ui_conn_panel6, 109);
    lv_obj_set_x(ui_conn_panel6, -1);
    lv_obj_set_y(ui_conn_panel6, 43);
    lv_obj_set_align(ui_conn_panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_conn_panel6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_conn_panel6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_conn_panel6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conn_panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_conn_panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_conn_panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_conn_panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp61 = lv_label_create(ui_conn_panel6);
    lv_obj_set_width(ui_connp61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_connp61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp61, "       Wifi\nConnected");
    lv_obj_set_style_text_color(ui_connp61, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp61, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp62 = lv_label_create(ui_conn_panel6);
    lv_obj_set_width(ui_connp62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp62, 0);
    lv_obj_set_y(ui_connp62, 55);
    lv_obj_set_align(ui_connp62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp62, "2s");
    lv_obj_set_style_text_color(ui_connp62, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp62, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp62, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conncancel = lv_btn_create(ui_Page_Connect);
    lv_obj_set_width(ui_conncancel, 60);
    lv_obj_set_height(ui_conncancel, 60);
    lv_obj_set_x(ui_conncancel, 0);
    lv_obj_set_y(ui_conncancel, 125);
    lv_obj_set_align(ui_conncancel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conncancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_conncancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_conncancel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_conncancel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conncancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_conncancel, &ui_img_button_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_conncancel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_conncancel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arrow1 = lv_img_create(ui_Page_Connect);
    lv_img_set_src(ui_arrow1, &ui_img_arrow_png);
    lv_obj_set_width(ui_arrow1, LV_SIZE_CONTENT);   /// 46
    lv_obj_set_height(ui_arrow1, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_arrow1, 130);
    lv_obj_set_y(ui_arrow1, 0);
    lv_obj_set_align(ui_arrow1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arrow1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_arrow1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_arrow2 = lv_img_create(ui_Page_Connect);
    lv_img_set_src(ui_arrow2, &ui_img_arrow_png);
    lv_obj_set_width(ui_arrow2, LV_SIZE_CONTENT);   /// 46
    lv_obj_set_height(ui_arrow2, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_arrow2, -130);
    lv_obj_set_y(ui_arrow2, 0);
    lv_obj_set_align(ui_arrow2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arrow2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_arrow2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_arrow2, 1800);

    lv_obj_add_event_cb(ui_conncancel, ui_event_conncancel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arrow1, ui_event_arrow1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arrow2, ui_event_arrow2, LV_EVENT_ALL, NULL);

}
