// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai

#include "../ui.h"

void ui_Page_ViewLive_screen_init(void)
{
    ui_Page_ViewLive = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_ViewLive, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_ViewLive, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_ViewLive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_viewlivp = lv_obj_create(ui_Page_ViewLive);
    lv_obj_set_width(ui_viewlivp, 412);
    lv_obj_set_height(ui_viewlivp, 412);
    lv_obj_set_align(ui_viewlivp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_viewlivp, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_viewlivp, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_viewlivp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_viewlivp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_viewlivp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_viewlivp, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_viewlivp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_viewlivp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_viewlivp, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_viewlivp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_livbtn1 = lv_btn_create(ui_viewlivp);
    lv_obj_set_width(ui_livbtn1, 150);
    lv_obj_set_height(ui_livbtn1, 60);
    lv_obj_set_x(ui_livbtn1, 0);
    lv_obj_set_y(ui_livbtn1, 1);
    lv_obj_set_align(ui_livbtn1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_livbtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_livbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_livbtn1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_livbtn1, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_livbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_livbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_livbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_liv1 = lv_label_create(ui_livbtn1);
    lv_obj_set_width(ui_liv1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_liv1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_liv1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_liv1, "End");
    lv_obj_set_style_text_font(ui_liv1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_livbtn2 = lv_btn_create(ui_viewlivp);
    lv_obj_set_width(ui_livbtn2, 60);
    lv_obj_set_height(ui_livbtn2, 60);
    lv_obj_set_x(ui_livbtn2, -1);
    lv_obj_set_y(ui_livbtn2, 26);
    lv_obj_set_align(ui_livbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_livbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_livbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_livbtn2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_livbtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_livbtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_livbtn2, &ui_img_button_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_livbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_livbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_localarm2 = lv_arc_create(ui_Page_ViewLive);
    lv_obj_set_width(ui_localarm2, 412);
    lv_obj_set_height(ui_localarm2, 412);
    lv_obj_set_align(ui_localarm2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_localarm2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_value(ui_localarm2, 100);
    lv_arc_set_bg_angles(ui_localarm2, 0, 360);
    lv_obj_set_style_arc_color(ui_localarm2, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_localarm2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_localarm2, 40, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_localarm2, &ui_img_gradient_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_localarm2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_localarm2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_viewlivp2 = lv_obj_create(ui_Page_ViewLive);
    lv_obj_set_width(ui_viewlivp2, 412);
    lv_obj_set_height(ui_viewlivp2, 412);
    lv_obj_set_align(ui_viewlivp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_viewlivp2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_viewlivp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_viewlivp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_viewlivp2, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_viewlivp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_viewlivp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_livt = lv_label_create(ui_viewlivp2);
    lv_obj_set_width(ui_livt, 350);
    lv_obj_set_height(ui_livt, 120);
    lv_obj_set_x(ui_livt, 0);
    lv_obj_set_y(ui_livt, 20);
    lv_obj_set_align(ui_livt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_livt, "Detected, sending to cloud to analysis");
    lv_obj_set_style_text_color(ui_livt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_livt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_livt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_livt, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_livbtn1, ui_event_livbtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_livbtn2, ui_event_livbtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page_ViewLive, ui_event_Page_ViewLive, LV_EVENT_ALL, NULL);

}
