// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: indoor_combo

#include "../ui.h"

void ui_screen_startup_screen_init(void)
{
ui_screen_startup = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_startup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_logo = lv_img_create(ui_screen_startup);
lv_img_set_src(ui_logo, &ui_img_seeed_logos_png);
lv_obj_set_width( ui_logo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_logo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_screen_startup, ui_event_screen_startup, LV_EVENT_ALL, NULL);

}
