// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: indoor_combo

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ui_startup
void ui_ui_startup_screen_init(void);
lv_obj_t *ui_ui_startup;
lv_obj_t *ui_logo;


// SCREEN: ui_ui_preview
void ui_ui_preview_screen_init(void);
lv_obj_t *ui_ui_preview;
lv_obj_t *ui_Arc2;


// SCREEN: ui_ui_setting
void ui_ui_setting_screen_init(void);
lv_obj_t *ui_ui_setting;
lv_obj_t *ui_setting;


// SCREEN: ui_ui_shutdown
void ui_ui_shutdown_screen_init(void);
lv_obj_t *ui_ui_shutdown;
lv_obj_t *ui_Image7;


// SCREEN: ui_ui_shutdown_confirm
void ui_ui_shutdown_confirm_screen_init(void);
lv_obj_t *ui_ui_shutdown_confirm;
lv_obj_t *ui_Image8;
lv_obj_t *ui_confirm;
lv_obj_t *ui_Label1;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ui_startup_screen_init();
ui_ui_preview_screen_init();
ui_ui_setting_screen_init();
ui_ui_shutdown_screen_init();
ui_ui_shutdown_confirm_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ui_startup);
}
