// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai

#ifndef _AI_UI_H
#define _AI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

extern lv_indev_t * cur_drv;
extern lv_group_t * g_main;
extern lv_timer_t * g_timer;
extern lv_obj_t   * g_prepage;

void start_anim_Animation(lv_obj_t * TargetObject, int delay);
void start_anim2_Animation(lv_obj_t * TargetObject, int delay);
void rec_task_Animation(lv_obj_t * TargetObject, int delay);
void text_pulse_Animation(lv_obj_t * TargetObject, int delay);
void gif_play_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_seeed_studio
void ui_seeed_studio_screen_init(void);
void ui_event_seeed_studio(lv_event_t * e);
extern lv_obj_t * ui_seeed_studio;
extern lv_obj_t * ui_startlogo;
// SCREEN: ui_virtual
void ui_virtual_screen_init(void);
void ui_event_virtual(lv_event_t * e);
extern lv_obj_t * ui_virtual;
// SCREEN: ui_mainscreen
void ui_mainscreen_screen_init(void);
extern lv_obj_t * ui_mainscreen;
extern lv_obj_t * ui_mainpanel;
extern lv_obj_t * ui_mainlist;
extern lv_obj_t * ui_mainlp1;
void ui_event_mainbtn1(lv_event_t * e);
extern lv_obj_t * ui_mainbtn1;
extern lv_obj_t * ui_mainlp2;
void ui_event_mainbtn2(lv_event_t * e);
extern lv_obj_t * ui_mainbtn2;
extern lv_obj_t * ui_mainlp3;
void ui_event_mainbtn3(lv_event_t * e);
extern lv_obj_t * ui_mainbtn3;
extern lv_obj_t * ui_mainlp4;
void ui_event_mainbtn4(lv_event_t * e);
extern lv_obj_t * ui_mainbtn4;
extern lv_obj_t * ui_maincircle;
extern lv_obj_t * ui_maincontent;
extern lv_obj_t * ui_maintitle;
extern lv_obj_t * ui_maintime;
extern lv_obj_t * ui_mainwifi;
extern lv_obj_t * ui_mainby;
// SCREEN: ui_nocurrentT
void ui_nocurrentT_screen_init(void);
extern lv_obj_t * ui_nocurrentT;
extern lv_obj_t * ui_notasktext;
void ui_event_notaskbtn(lv_event_t * e);
extern lv_obj_t * ui_notaskbtn;
extern lv_obj_t * ui_notasklabel;
// SCREEN: ui_waitingtask
void ui_waitingtask_screen_init(void);
void ui_event_waitingtask(lv_event_t * e);
extern lv_obj_t * ui_waitingtask;
extern lv_obj_t * ui_waittext;
extern lv_obj_t * ui_waitspinner;
// SCREEN: ui_atask_down
void ui_atask_down_screen_init(void);
void ui_event_atask_down(lv_event_t * e);
extern lv_obj_t * ui_atask_down;
extern lv_obj_t * ui_ataskd_text;
extern lv_obj_t * ui_atask_arc2;
extern lv_obj_t * ui_atask_sec3;
extern lv_obj_t * ui_atask_sec2;
extern lv_obj_t * ui_atask_sec1;
extern lv_obj_t * ui_atask_press;
// SCREEN: ui_preview_detection
void ui_preview_detection_screen_init(void);
void ui_event_preview_detection(lv_event_t * e);
extern lv_obj_t * ui_preview_detection;
extern lv_obj_t * ui_predetp1;
void ui_event_predet1v(lv_event_t * e);
extern lv_obj_t * ui_predet1v;
extern lv_obj_t * ui_predet1vt;
void ui_event_predet1e(lv_event_t * e);
extern lv_obj_t * ui_predet1e;
extern lv_obj_t * ui_predet1et;
void ui_event_predet1c(lv_event_t * e);
extern lv_obj_t * ui_predet1c;
extern lv_obj_t * ui_predetp2;
void ui_event_predet2b(lv_event_t * e);
extern lv_obj_t * ui_predet2b;
extern lv_obj_t * ui_predet2bt;
void ui_event_predet2e(lv_event_t * e);
extern lv_obj_t * ui_predet2e;
extern lv_obj_t * ui_predet2et;
void ui_event_predet2c(lv_event_t * e);
extern lv_obj_t * ui_predet2c;
extern lv_obj_t * ui_predetp3;
void ui_event_predet3e(lv_event_t * e);
extern lv_obj_t * ui_predet3e;
extern lv_obj_t * ui_predet3et;
void ui_event_predet3c(lv_event_t * e);
extern lv_obj_t * ui_predet3c;
void ui_event_previewp1(lv_event_t * e);
extern lv_obj_t * ui_previewp1;
void ui_event_previewp2(lv_event_t * e);
extern lv_obj_t * ui_previewp2;
// SCREEN: ui_ltaskscreen
void ui_ltaskscreen_screen_init(void);
extern lv_obj_t * ui_ltaskscreen;
extern lv_obj_t * ui_menupanel;
extern lv_obj_t * ui_menulist;
extern lv_obj_t * ui_menulp1;
void ui_event_menubtn1(lv_event_t * e);
extern lv_obj_t * ui_menubtn1;
extern lv_obj_t * ui_menulp2;
void ui_event_menubtn2(lv_event_t * e);
extern lv_obj_t * ui_menubtn2;
extern lv_obj_t * ui_menulp3;
void ui_event_menubtn3(lv_event_t * e);
extern lv_obj_t * ui_menubtn3;
extern lv_obj_t * ui_menulp4;
void ui_event_menubtn4(lv_event_t * e);
extern lv_obj_t * ui_menubtn4;
extern lv_obj_t * ui_menucircle;
extern lv_obj_t * ui_menucontent;
// SCREEN: ui_ltask_view
void ui_ltask_view_screen_init(void);
void ui_event_ltask_view(lv_event_t * e);
extern lv_obj_t * ui_ltask_view;
// SCREEN: ui_ltask_back
void ui_ltask_back_screen_init(void);
extern lv_obj_t * ui_ltask_back;
void ui_event_ltaskbb1(lv_event_t * e);
extern lv_obj_t * ui_ltaskbb1;
extern lv_obj_t * ui_ltaskbb1t;
void ui_event_ltaskbb2(lv_event_t * e);
extern lv_obj_t * ui_ltaskbb2;
// SCREEN: ui_ha
void ui_ha_screen_init(void);
void ui_event_ha(lv_event_t * e);
extern lv_obj_t * ui_ha;
extern lv_obj_t * ui_TempTitle;
extern lv_obj_t * ui_RHTitle;
extern lv_obj_t * ui_TempVal;
extern lv_obj_t * ui_RHVal;
extern lv_obj_t * ui_TempSy;
extern lv_obj_t * ui_RHSy;
extern lv_obj_t * ui_hapanel1;
extern lv_obj_t * ui_habtn1t;
extern lv_obj_t * ui_habtn1;
extern lv_obj_t * ui_hapanel2;
extern lv_obj_t * ui_habtn2t;
extern lv_obj_t * ui_habtn2;
// SCREEN: ui_setting
void ui_setting_screen_init(void);
void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_logo_png);    // assets\logo.png
LV_IMG_DECLARE(ui_img_onboard_demo_png);    // assets\onboard Demo.png
LV_IMG_DECLARE(ui_img_19533631);    // assets\onboard Demo-2.png
LV_IMG_DECLARE(ui_img_current_task_png);    // assets\current task.png
LV_IMG_DECLARE(ui_img_1721754357);    // assets\current task-2.png
LV_IMG_DECLARE(ui_img_2022210068);    // assets\HA-2.png
LV_IMG_DECLARE(ui_img_ha_png);    // assets\HA.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets\setting.png
LV_IMG_DECLARE(ui_img_457376777);    // assets\setting-2.png
LV_IMG_DECLARE(ui_img_wifi_4_png);    // assets\wifi_4.png
LV_IMG_DECLARE(ui_img_battery_5_png);    // assets\battery_5.png
LV_IMG_DECLARE(ui_img_cancel_png);    // assets\cancel.png
LV_IMG_DECLARE(ui_img_human1_png);    // assets\human1.png
LV_IMG_DECLARE(ui_img_human2_png);    // assets\human2.png
LV_IMG_DECLARE(ui_img_apple1_png);    // assets\apple1.png
LV_IMG_DECLARE(ui_img_apple2_png);    // assets\apple2.png
LV_IMG_DECLARE(ui_img_gesture1_png);    // assets\gesture1.png
LV_IMG_DECLARE(ui_img_gesture2_png);    // assets\gesture2.png
LV_IMG_DECLARE(ui_img_back1_png);    // assets\back1.png
LV_IMG_DECLARE(ui_img_back2_png);    // assets\back2.png
LV_IMG_DECLARE(ui_img_setting__png);    // assets\setting_.png
LV_IMG_DECLARE(ui_img_appled1_png);    // assets\appled1.png
LV_IMG_DECLARE(ui_img_appled2_png);    // assets\appled2.png
LV_IMG_DECLARE(ui_img_appled3_png);    // assets\appled3.png
LV_IMG_DECLARE(ui_img_battery_1_png);    // assets\battery_1.png
LV_IMG_DECLARE(ui_img_battery_2_png);    // assets\battery_2.png
LV_IMG_DECLARE(ui_img_battery_3_png);    // assets\battery_3.png
LV_IMG_DECLARE(ui_img_battery_4_png);    // assets\battery_4.png
LV_IMG_DECLARE(ui_img_gesture_detection1_png);    // assets\Gesture Detection1.png
LV_IMG_DECLARE(ui_img_gesture_detection2_png);    // assets\Gesture Detection2.png
LV_IMG_DECLARE(ui_img_gesture_detection3_png);    // assets\Gesture Detection3.png
LV_IMG_DECLARE(ui_img_gesture_detection4_png);    // assets\Gesture Detection4.png
LV_IMG_DECLARE(ui_img_gesture_detection5_png);    // assets\Gesture Detection5.png
LV_IMG_DECLARE(ui_img_gesture_detection6_png);    // assets\Gesture Detection6.png
LV_IMG_DECLARE(ui_img_humand1_png);    // assets\humand1.png
LV_IMG_DECLARE(ui_img_humand2_png);    // assets\humand2.png
LV_IMG_DECLARE(ui_img_humand3_png);    // assets\humand3.png
LV_IMG_DECLARE(ui_img_humand4_png);    // assets\humand4.png
LV_IMG_DECLARE(ui_img_virtual1_png);    // assets\virtual1.png
LV_IMG_DECLARE(ui_img_virtual2_png);    // assets\virtual2.png
LV_IMG_DECLARE(ui_img_virtual3_png);    // assets\virtual3.png
LV_IMG_DECLARE(ui_img_virtual4_png);    // assets\virtual4.png
LV_IMG_DECLARE(ui_img_virtual5_png);    // assets\virtual5.png
LV_IMG_DECLARE(ui_img_virtual6_png);    // assets\virtual6.png
LV_IMG_DECLARE(ui_img_wifi_0_png);    // assets\wifi_0.png
LV_IMG_DECLARE(ui_img_wifi_1_png);    // assets\wifi_1.png
LV_IMG_DECLARE(ui_img_wifi_2_png);    // assets\wifi_2.png
LV_IMG_DECLARE(ui_img_wifi_3_png);    // assets\wifi_3.png

LV_FONT_DECLARE(ui_font_Font1);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
