// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai
#include "esp_log.h"
#include "data_defs.h"
#include "event_loops.h"
#include "esp_wifi.h"
#include <dirent.h>
#include "esp_timer.h"

#include "ui/ui.h"
#include "pm.h"
#include "animation.h"

#include "app_device_info.h"
#include "app_ble.h"
#include "app_wifi.h"
#include "storage.h"
#include "app_png.h"
#include "sensecap-watcher.h"

#define VOLBRI_CFG "volbri-cfg"

static const char *TAG = "ui_event";
static const char *CLICK_TAG = "Click_event";

wifi_ap_record_t wifi_record;
int first_use = 0;
uint8_t task_down = 0;
uint8_t guide_step = 0;
uint8_t swipe_id = 0; // 0 for shutdown, 1 for factoryreset
static bool is_charging = 0;
static uint8_t loading_flag = 0;
static struct view_data_setting_volbri volbri;
static struct view_data_setting_switch set_sw;
static struct view_data_emoticon_display emo_disp;

static int file_idx = 0;
static int current_img_index = 0;
static uint32_t local_task_id;
static lv_timer_t *g_timer;

extern char sn_data[66];
extern uint8_t wifi_page_id;
extern uint8_t shutdown_state;
extern uint8_t emoticon_disp_id; // for lv_async switch and emoticon switch
extern lv_obj_t *ui_alarm_indicator;

extern lv_img_dsc_t *g_detect_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_speak_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_listen_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_load_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_sleep_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_smile_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_detected_img_dsc[MAX_IMAGES];

extern int g_detect_image_count;
extern int g_speak_image_count;
extern int g_listen_image_count;
extern int g_load_image_count;
extern int g_sleep_image_count;
extern int g_smile_image_count;
extern int g_detected_image_count;

extern GroupInfo group_page_main;
extern GroupInfo group_page_template;
extern GroupInfo group_page_set;
extern GroupInfo group_page_view;
extern GroupInfo group_page_ha;
extern GroupInfo group_page_brightness;
extern GroupInfo group_page_volume;

static void Page_ConnAPP_BLE();
static void Page_ConnAPP_Mate();
static void Task_end();
static void Page_shutdown();
static void Page_facreset();
static void settingInfoInit();

static void async_img_switch_vir(void *arg)
{
    lv_img_dsc_t *current_img = (lv_img_dsc_t *)arg;
    lv_obj_set_style_bg_img_src(ui_Page_Vir, current_img, LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void async_img_switch_viewava(void *arg)
{
    lv_img_dsc_t *current_img = (lv_img_dsc_t *)arg;
    lv_obj_set_style_bg_img_src(ui_Page_ViewAva, current_img, LV_PART_MAIN | LV_STATE_DEFAULT);
}

static uint8_t vir_load_count = 0;
static void smile_timer_callback(lv_timer_t *timer)
{
    current_img_index = (current_img_index + 1) % g_smile_image_count;
    lv_img_dsc_t *current_img = g_smile_img_dsc[current_img_index];
    if (emoticon_disp_id)
    {
        async_img_switch_vir(current_img);
    }
    else
    {
        lv_async_call(async_img_switch_vir, current_img);
    }
    vir_load_count ++;
    // if delay 2s and the device is not wifi-configed
    if(vir_load_count>4 && (!wifi_page_id))
    {
        lv_event_send(ui_Page_Vir, LV_EVENT_CLICKED, NULL);
    }
}

static void detect_timer_callback(lv_timer_t *timer)
{
    current_img_index = (current_img_index + 1) % g_detect_image_count;
    lv_img_dsc_t *current_img = g_detect_img_dsc[current_img_index];
    if (emoticon_disp_id)
    {
        async_img_switch_viewava(current_img);
    }
    else
    {
        lv_async_call(async_img_switch_viewava, current_img);
    }
}

static void listen_timer_callback(lv_timer_t *timer)
{
    current_img_index = (current_img_index + 1) % g_listen_image_count;
    lv_img_dsc_t *current_img = g_listen_img_dsc[current_img_index];
    if (emoticon_disp_id)
    {
        async_img_switch_viewava(current_img);
    }
    else
    {
        lv_async_call(async_img_switch_viewava, current_img);
    }
}

static void detected_timer_callback(lv_timer_t *timer)
{
    current_img_index = (current_img_index + 1) % g_detected_image_count;
    lv_img_dsc_t *current_img = g_detect_img_dsc[current_img_index];
    if (emoticon_disp_id)
    {
        async_img_switch_viewava(current_img);
    }
    else
    {
        lv_async_call(async_img_switch_viewava, current_img);
    }
}

static void sleep_timer_callback(lv_timer_t *timer)
{
    current_img_index = (current_img_index + 1) % g_sleep_image_count;
    lv_img_dsc_t *current_img = g_sleep_img_dsc[current_img_index];
    if (emoticon_disp_id)
    {
        async_img_switch_viewava(current_img);
    }
    else
    {
        lv_async_call(async_img_switch_viewava, current_img);
    }
}

static void speak_timer_callback(lv_timer_t *timer)
{
    current_img_index = (current_img_index + 1) % g_speak_image_count;
    lv_img_dsc_t *current_img = g_speak_img_dsc[current_img_index];
    if (emoticon_disp_id)
    {
        async_img_switch_viewava(current_img);
    }
    else
    {
        lv_async_call(async_img_switch_viewava, current_img);
    }
}

static void create_timer(uint8_t det_task)
{
    if (g_timer != NULL)
    {
        lv_timer_del(g_timer);
        g_timer = NULL;
    }
    switch (det_task)
    {
        case 0:
            g_timer = lv_timer_create(smile_timer_callback, 800, NULL);
            break;
        case 1:
            g_timer = lv_timer_create(detect_timer_callback, 800, NULL);
            break;
        case 2:
            g_timer = lv_timer_create(listen_timer_callback, 800, NULL);
            break;
        case 3:
            g_timer = lv_timer_create(detected_timer_callback, 800, NULL);
            break;
        case 4:
            g_timer = lv_timer_create(sleep_timer_callback, 800, NULL);
            break;
        case 5:
            g_timer = lv_timer_create(speak_timer_callback, 800, NULL);
            break;
        case 6:
            // lv_timer_pause(g_timer);
            break;
        default:
            break;
    }
}

void slbattery_cb(lv_event_t *e) { }

static void set_obj_style_defocused(lv_obj_t *obj, lv_obj_t *obj_text)
{
    lv_obj_set_width(obj, 412);
    lv_obj_set_height(obj, 50);
    lv_obj_set_style_radius(obj, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(obj, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(obj_text, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void set_obj_style_focused(lv_obj_t *obj, lv_obj_t *obj_text)
{
    lv_obj_set_width(obj, 380);
    lv_obj_set_height(obj, 90);
    lv_obj_set_style_radius(obj, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(obj, lv_color_hex(0xA9DE2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(obj, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(obj_text, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void startload_cb(lv_event_t *e)
{
    _ui_screen_change(&ui_Page_loading, LV_SCR_LOAD_ANIM_FADE_ON, 100, 3000, &ui_Page_loading_screen_init);
}

void loadsl_cb(lv_event_t *e)
{
    if (loading_flag == 0)
    {
        _ui_opacity_set(ui_Left1, 0);
        _ui_opacity_set(ui_Left2, 0);
        _ui_opacity_set(ui_Left3, 0);
        _ui_opacity_set(ui_Left4, 0);
        _ui_opacity_set(ui_Left5, 0);
        _ui_opacity_set(ui_Left5, 0);
        _ui_opacity_set(ui_Left6, 0);
        _ui_opacity_set(ui_Left7, 0);
        _ui_opacity_set(ui_Left8, 0);
        _ui_opacity_set(ui_Right1, 0);
        _ui_opacity_set(ui_Right8, 0);
        _ui_opacity_set(ui_Right2, 0);
        _ui_opacity_set(ui_Right3, 0);
        _ui_opacity_set(ui_Right4, 0);
        _ui_opacity_set(ui_Right5, 0);
        _ui_opacity_set(ui_Right6, 0);
        _ui_opacity_set(ui_Right7, 0);

        lv_obj_clear_flag(ui_Left1, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left3, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left4, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left5, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left6, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left7, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left8, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right1, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right3, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right4, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right5, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right6, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right7, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right8, LV_OBJ_FLAG_HIDDEN);

        sidelines_Animation(ui_Left1, 0);
        secondline_Animation(ui_Left2, 1000);
        shorttoptobottom_Animation(ui_Left3, 1500);
        shorttoptobottom_Animation(ui_Left4, 2500);
        secondline_Animation(ui_Left5, 5000);
        sidelines_Animation(ui_Left6, 5500);
        shortbottomtotop_Animation(ui_Left8, 3000);
        shortbottomtotop_Animation(ui_Left7, 4000);
        loading_flag++;
    }
    else if (loading_flag == 1)
    {
        sidelines_Animation(ui_Right1, 0);
        secondline_Animation(ui_Right2, 1000);
        shorttoptobottom_Animation(ui_Right3, 1500);
        shorttoptobottom_Animation(ui_Right4, 2500);
        secondline_Animation(ui_Right5, 5000);
        sidelines_Animation(ui_Right6, 5500);
        shortbottomtotop_Animation(ui_Right8, 3000);
        shortbottomtotop_Animation(ui_Right7, 4000);
        loading_flag++;
    }
}

void virtc_cb(lv_event_t *e)
{
    // ESP_LOGI(CLICK_TAG, "virtc_cb");
    if(!wifi_page_id)   // if the device is not wifi-configed, then appear Connect APP panel
    {
        lv_obj_clear_flag(ui_virp, LV_OBJ_FLAG_HIDDEN);
        create_timer(6);    // stop timer
    }else{              // else the device is wifi-configed, then page jump to main page
        lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
        create_timer(6);    // stop timer
    }
}

void virtsl_cb(lv_event_t *e)
{
    lv_obj_add_flag(ui_virp, LV_OBJ_FLAG_HIDDEN);
    lv_group_add_obj(g_main, ui_Page_Vir);
    create_timer(0);
    lv_group_set_wrap(g_main, false);
    get_usage_guide(UI_CALLER);
}

void virb1c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "virb1c_cb");
    settingInfoInit(); 
    create_timer(6);
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_Connect, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Connect_screen_init);
    Page_ConnAPP_Mate();
}

void virb2c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "virb2c_cb");
    settingInfoInit();
    create_timer(6);
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void main1c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "main1c_cb");
    lv_pm_open_page(g_main, &group_page_template, PM_ADD_OBJS_TO_GROUP, &ui_Page_LocTask, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_LocTask_screen_init);
    lv_group_focus_obj(ui_menubtn2);
}

void main1f_cb(lv_event_t *e)
{
    lv_obj_set_y(ui_maintitle, 0);
    lv_label_set_text(ui_maintitle, "Task\nTemplates");
}

void main2c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "main2c_cb");
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_CurTask1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_CurTask1_screen_init);
}

void main2f_cb(lv_event_t *e)
{
    lv_obj_set_y(ui_maintitle, 0);
    lv_label_set_text(ui_maintitle, "Current\nTasks");
}

void main3c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "main3c_cb");
    lv_pm_open_page(g_main, &group_page_ha, PM_ADD_OBJS_TO_GROUP, &ui_Page_HA, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_HA_screen_init);
}

void main3f_cb(lv_event_t *e)
{
    lv_obj_set_y(ui_maintitle, 20);
    lv_label_set_text(ui_maintitle, "Extension");
}

void main4c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "main4c_cb");
    settingInfoInit();
    lv_pm_open_page(g_main, &group_page_set, PM_ADD_OBJS_TO_GROUP, &ui_Page_Set, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Set_screen_init);
}

void main4f_cb(lv_event_t *e)
{
    lv_obj_set_y(ui_maintitle, 20);
    lv_label_set_text(ui_maintitle, "Setting");
}

void connc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "connc_cb");
    lv_pm_open_page(g_main, &group_page_set, PM_ADD_OBJS_TO_GROUP, &ui_Page_Set, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Set_screen_init);
    lv_obj_add_flag(ui_wifip2, LV_OBJ_FLAG_HIDDEN);
}

void arr1c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "arr1c_cb");
    Page_ConnAPP_BLE();
}

void arr1f_cb(lv_event_t *e) 
{
    // Page_ConnAPP_BLE();
}

void arr2c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "arr2c_cb");
    Page_ConnAPP_Mate();
}

void arr2f_cb(lv_event_t *e) 
{ 
    // Page_ConnAPP_Mate();
}

void ntaskb1c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "ntaskb1c_cb");
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_CurTask2, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_CurTask2_screen_init);
}

void ntaskb2c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "ntaskb2c_cb");
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void waitbc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "waitbc_cb");
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_STOP, NULL, NULL, portMAX_DELAY);
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void revbc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "revbc_cb");
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_STOP, NULL, NULL, portMAX_DELAY);
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void viewac_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "viewac_cb");
    if(first_use || guide_step == 2)
    {
        lv_obj_clear_flag(ui_viewavap, LV_OBJ_FLAG_HIDDEN); /// Flags
        lv_obj_move_foreground(ui_viewavap);
    }
}

void viewaf_cb(lv_event_t *e)
{
    lv_obj_add_flag(ui_alarm_indicator, LV_OBJ_FLAG_HIDDEN);
    _ui_screen_change(&ui_Page_ViewAva, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_ViewAva_screen_init);
}

void viewasl_cb(lv_event_t *e)
{
    if (emoticon_disp_id == 1)
    {
        create_timer(3); // Load timer for the "detected" animation when emoticon_disp_id is 1
        if (!first_use)
        {
            if (guide_step == 2)
            {
                lv_img_set_src(ui_guideimg1, &ui_img_onboardclick_png);
                lv_obj_add_flag(ui_viewavap2, LV_OBJ_FLAG_CLICKABLE);
                lv_group_remove_all_objs(g_main);
                lv_group_add_obj(g_main, ui_viewavap2);
            }
            else if (guide_step == 0)
            {
                guide_step = 1;
                lv_obj_clear_flag(ui_viewavap2, LV_OBJ_FLAG_HIDDEN);
                lv_obj_move_foreground(ui_viewavap2);
            }
        }
    }
    else
    {
        create_timer(5); // Load timer for the "speak" animation when emoticon_disp_id is 0
        if (!first_use)
        {
            if (guide_step == 2)
            {
                lv_img_set_src(ui_guideimg1, &ui_img_onboardclick_png);
                lv_obj_add_flag(ui_viewavap2, LV_OBJ_FLAG_CLICKABLE);
                lv_group_remove_all_objs(g_main);
                lv_group_add_obj(g_main, ui_viewavap2);
            }
            else if (guide_step == 0)
            {
                guide_step = 1;
                lv_obj_clear_flag(ui_viewavap2, LV_OBJ_FLAG_HIDDEN);
                lv_obj_move_foreground(ui_viewavap2);
            }
        }
    }
}

void viewasul_cb(lv_event_t *e)
{
    create_timer(6);
}

void ava1c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "ava1c_cb");
    Task_end();
}

void ava2c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "ava2c_cb");
    lv_obj_add_flag(ui_viewavap, LV_OBJ_FLAG_HIDDEN); /// Flags
}

void avagc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "avagc_cb");
    if (guide_step == 2)
    {
        lv_obj_add_flag(ui_viewavap2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_viewlivp3, LV_OBJ_FLAG_HIDDEN);
        lv_event_send(ui_Page_ViewAva, LV_EVENT_CLICKED, NULL);
        guide_step = 3;
        set_usage_guide(UI_CALLER, 1);
        get_usage_guide(UI_CALLER);
        lv_group_remove_all_objs(g_main);
        lv_group_add_obj(g_main, ui_Page_ViewAva);
        lv_group_add_obj(g_main, ui_Page_ViewLive);
    }
}

void viewlc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "viewlc_cb");
    if(first_use)
    {
        lv_obj_clear_flag(ui_viewlivp, LV_OBJ_FLAG_HIDDEN); /// Flags
        lv_obj_move_foreground(ui_viewlivp);
    }
}

void viewlf_cb(lv_event_t *e)
{
    _ui_screen_change(&ui_Page_ViewLive, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_ViewLive_screen_init);
}

void viewlsl_cb(lv_event_t *e)
{
    if ((!first_use) && (guide_step != 3))
    {
        guide_step = 2;
        // vTaskDelay(2000 / portTICK_PERIOD_MS);
        lv_obj_clear_flag(ui_viewlivp3, LV_OBJ_FLAG_HIDDEN);
        lv_obj_move_foreground(ui_viewlivp3);
    }
}

void viewlsul_cb(lv_event_t *e) 
{
}

void liv1c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "liv1c_cb");
    Task_end();
}

void liv2c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "liv2c_cb");
    lv_obj_add_flag(ui_viewlivp, LV_OBJ_FLAG_HIDDEN); /// Flags
}

void waitT_cb(lv_event_t *e)
{
    // Your code here
}

void loctask1c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "loctask1c_cb");
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void loctask1f_cb(lv_event_t *e)
{
    lv_label_set_text(ui_Label1, "");
    lv_obj_add_flag(ui_mimgp, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_mtext, LV_OBJ_FLAG_HIDDEN);
}

void loctask1df_cb(lv_event_t *e)
{
    lv_obj_clear_flag(ui_mimgp, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_mtext, LV_OBJ_FLAG_HIDDEN);
}

void loctask2c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "loctask2c_cb");
    local_task_id = 2;
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_START_BY_LOCAL, &local_task_id, sizeof(local_task_id), portMAX_DELAY);
    lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_ViewAva_screen_init);
}

void loctask2f_cb(lv_event_t *e)
{
    lv_label_set_text(ui_Label1, "Human\nDetection");
    lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_human_d_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void loctask3c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "loctask3c_cb");
    local_task_id = 1;
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_START_BY_LOCAL, &local_task_id, sizeof(local_task_id), portMAX_DELAY);
    lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_ViewAva_screen_init);
}

void loctask3f_cb(lv_event_t *e)
{
    lv_label_set_text(ui_Label1, "Pet\nDetection");
    lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_dog_d_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void loctask4c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "loctask4c_cb");
    local_task_id = 0;
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_START_BY_LOCAL, &local_task_id, sizeof(local_task_id), portMAX_DELAY);
    lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_ViewAva_screen_init);
}

void loctask4f_cb(lv_event_t *e)
{
    lv_label_set_text(ui_Label1, "Gesture\nDetection");
    lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_gesture_d_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void locavac_cb(lv_event_t *e) { }

void loclivc_cb(lv_event_t *e) { }

void sgesup_cb(lv_event_t *e)
{
    lv_group_focus_next(g_main);
}

void sgesdown_cb(lv_event_t *e)
{
    lv_group_focus_prev(g_main);
}

void sclick_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "sclick_cb");
    lv_obj_t *focused_obj = lv_group_get_focused(g_main);
    lv_event_send(focused_obj, LV_EVENT_CLICKED, NULL);
}

void mgesup_cb(lv_event_t *e)
{
    lv_group_focus_next(g_main);
}

void mgesdown_cb(lv_event_t *e)
{
    lv_group_focus_prev(g_main);
}

void vieback_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "vieback_cb");
    lv_obj_add_flag(ui_viewlivp2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_alarm_indicator, LV_OBJ_FLAG_HIDDEN);
}

void livgc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "livgc_cb");
    // lv_obj_add_flag(ui_viewavap2, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_viewlivp3, LV_OBJ_FLAG_HIDDEN);
}

void lgesleft_cb(lv_event_t *e)
{
    lv_group_focus_next(g_main);
}

void lgesright_cb(lv_event_t *e)
{
    lv_group_focus_prev(g_main);
}

void mclick_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "mclick_cb");
    lv_obj_t *focused_obj = lv_group_get_focused(g_main);
    lv_event_send(focused_obj, LV_EVENT_CLICKED, NULL);
}

void lclick_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "lclick_cb");
    lv_obj_t *focused_obj = lv_group_get_focused(g_main);
    lv_event_send(focused_obj, LV_EVENT_CLICKED, NULL);
}

void lunlds_cb(lv_event_t *e) { }

void lunlded_cb(lv_event_t *e) { }

void custb1c_cb(lv_event_t *e) { }

void custb1f_cb(lv_event_t *e) { }

void custb1df_cb(lv_event_t *e) { }

void custb2c_cb(lv_event_t *e) { }

void custb2f_cb(lv_event_t *e) { }

void custb2df_cb(lv_event_t *e) { }

void custb3c_cb(lv_event_t *e) { }

void custb3f_cb(lv_event_t *e) { }

void custb3df_cb(lv_event_t *e) { }

void setbackf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setback, ui_setbackt);
}

void setbackdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setback, ui_setbackt);
}

void setdevf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setdev, ui_setdevt);
}

void setdevdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setdev, ui_setdevt);
}

void setwifif_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setwifi, ui_setwifit);
}

void setwifidf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setwifi, ui_setwifit);
}

void setrgbf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setrgb, ui_setrgbt);
    lv_obj_clear_flag(ui_setrgbsw, LV_OBJ_FLAG_HIDDEN);
}

void setrgbdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setrgb, ui_setrgbt);
    lv_obj_add_flag(ui_setrgbsw, LV_OBJ_FLAG_HIDDEN);
}

void setdownf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setdown, ui_setdownt);
}

void setdowndf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setdown, ui_setdownt);
}

void setblef_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setble, ui_setblet);
    lv_obj_clear_flag(ui_setblesw, LV_OBJ_FLAG_HIDDEN);
}

void setbledf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setble, ui_setblet);
    lv_obj_add_flag(ui_setblesw, LV_OBJ_FLAG_HIDDEN);
}

void setvolc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setvolc_cb");
    lv_label_set_text(ui_bvtitle, "Sound");
    lv_label_set_text(ui_bvbt, "Volume");
    lv_img_set_src(ui_bvbimg, &ui_img_volicon_png);
    lv_obj_add_flag(ui_bp, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_vp, LV_OBJ_FLAG_HIDDEN);

    lv_pm_open_page(g_main, &group_page_volume, PM_ADD_OBJS_TO_GROUP, &ui_Page_brivol, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_brivol_screen_init);
    lv_event_send(ui_vslider, LV_EVENT_VALUE_CHANGED, NULL);
}

void setvolf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setvol, ui_setvolt);
}

void setvoldf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setvol, ui_setvolt);
}

void setbric_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setbric_cb");
    lv_label_set_text(ui_bvtitle, "Display");
    lv_label_set_text(ui_bvbt, "Brightness");
    lv_img_set_src(ui_bvbimg, &ui_img_brighticon_png);
    lv_obj_clear_flag(ui_bp, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_vp, LV_OBJ_FLAG_HIDDEN);

    lv_pm_open_page(g_main, &group_page_brightness, PM_ADD_OBJS_TO_GROUP, &ui_Page_brivol, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_brivol_screen_init);
    lv_event_send(ui_bslider, LV_EVENT_VALUE_CHANGED, NULL);
}

void setbrif_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setbri, ui_setbrit);
}

void setbridf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setbri, ui_setbrit);
}

void setwwf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setww, ui_setwwt);
    lv_obj_clear_flag(ui_setwwsw, LV_OBJ_FLAG_HIDDEN);
}

void setwwdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setww, ui_setwwt);
    lv_obj_add_flag(ui_setwwsw, LV_OBJ_FLAG_HIDDEN);
}

void settimec_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "settimec_cb");
    lv_pm_open_page(g_main, NULL, PM_ADD_OBJS_TO_GROUP, &ui_Page_Slpt, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Slpt_screen_init);
}

void settimef_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_settime, ui_settimt);
}

void settimedf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_settime, ui_settimt);
}

void setfacf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setfac, ui_setfact);
}

void setfacdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setfac, ui_setfact);
}

void abdnf_cb(lv_event_t *e) { }

void abdndf_cb(lv_event_t *e) { }

void absvf_cb(lv_event_t *e) { }

void absvdf_cb(lv_event_t *e) { }

void absnf_cb(lv_event_t *e) { }

void absndf_cb(lv_event_t *e) { }

void abeuif_cb(lv_event_t *e) { }

void abeuidf_cb(lv_event_t *e) { }

void abblef_cb(lv_event_t *e) { }

void abbledf_cb(lv_event_t *e) { }

void paboutc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "paboutc_cb");
    lv_pm_open_page(g_main, &group_page_set, PM_ADD_OBJS_TO_GROUP, &ui_Page_Set, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Set_screen_init);
}

void setbackc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setbackc_cb");
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void setdevc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setdevc_cb");
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_SAbout, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_SAbout_screen_init);
}

void setwific_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setwific_cb");
    current_wifi_get(&wifi_record);
    static char ssid_string[34];
    strncpy(ssid_string, (const char *)wifi_record.ssid, sizeof(ssid_string) - 1);
    ssid_string[sizeof(ssid_string) - 1] = '\0';
    lv_label_set_text(ui_wifissid, ssid_string);
    // binded
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_Wifi, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Wifi_screen_init);
    lv_obj_clear_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_move_foreground(ui_wifiicon);
    lv_obj_add_flag(ui_wifip2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);

    if (!wifi_page_id)
    {
        lv_label_set_text(ui_wifissid, "None");
    }
}

void setblec_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setblec_cb");
    static lv_state_t btn_state;
    btn_state = lv_obj_get_state(ui_setblesw);
    switch (btn_state)
    {
        case 0:
            lv_obj_add_state(ui_setblesw, LV_STATE_CHECKED);
            // ESP_LOGI(TAG, "ble_btn_status: off");
            set_ble_status(UI_CALLER, 1);
            break;
        case 1:
            lv_obj_clear_state(ui_setblesw, LV_STATE_CHECKED);
            // ESP_LOGI(TAG, "ble_btn_status: on");
            set_ble_status(UI_CALLER, 0);
            break;

        default:
            break;
    }
}

void setrgbc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setrgbc_cb");
    static lv_state_t btn_state;
    btn_state = lv_obj_get_state(ui_setrgbsw);
    switch (btn_state)
    {
        case 0:
            ESP_LOGI(TAG, "rgb_switch: on");
            lv_obj_add_state(ui_setrgbsw, LV_STATE_CHECKED);
            set_rgb_switch(UI_CALLER, 1);

            break;
        case 1:
            ESP_LOGI(TAG, "rgb_switch: off");
            lv_obj_clear_state(ui_setrgbsw, LV_STATE_CHECKED);
            set_rgb_switch(UI_CALLER, 0);

            break;

        default:
            break;
    }
}

void setwwc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setwwc_cb");
    static lv_state_t btn_state;
    btn_state = lv_obj_get_state(ui_setwwsw);
    switch (btn_state)
    {
        case 0:
            lv_obj_add_state(ui_setwwsw, LV_STATE_CHECKED);

            break;
        case 1:
            lv_obj_clear_state(ui_setwwsw, LV_STATE_CHECKED);

            break;

        default:
            break;
    }
}

void setdownc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setdownc_cb");
    swipe_id = 0;
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_Swipe, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Swipe_screen_init);
    lv_slider_set_value(ui_spsilder, 0, LV_ANIM_ON);
    Page_shutdown();
}

void setfac_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setfac_cb");
    swipe_id = 1;
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_Swipe, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Swipe_screen_init);
    lv_slider_set_value(ui_spsilder, 0, LV_ANIM_ON);
    Page_facreset();
}

void setappf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setapp, ui_setappt);
}

void setappdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setapp, ui_setappt);
}

void setappc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setappc_cb");
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_Connect, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Connect_screen_init);
    Page_ConnAPP_Mate();
}

void slidervc_cb(lv_event_t *e)
{
    static int32_t slider_value;
    slider_value = lv_slider_get_value(ui_spsilder);
    if (slider_value > 80)
    {
        lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xFF5656), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_shadow_color(ui_spsilder, lv_color_hex(0xFF5656), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xFF5656), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    }
    else
    {
        lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_shadow_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    }
}

void sliderr_cb(lv_event_t *e)
{
    static int32_t slider_value;
    slider_value = lv_slider_get_value(ui_spsilder);
    if (slider_value > 80)
    {
        switch (swipe_id)
        {
            case 0:
                if (shutdown_state == 0)
                {
                    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_REBOOT, NULL, 0, portMAX_DELAY);
                }
                if (shutdown_state == 1)
                {
                    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_SHUTDOWN, NULL, 0, portMAX_DELAY);
                }
                break;

            case 1:
                set_reset_factory();
                break;

            default:
                break;
        }
    }
}

void preset_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "preset_cb");
    lv_pm_open_page(g_main, &group_page_set, PM_ADD_OBJS_TO_GROUP, &ui_Page_Set, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Set_screen_init);
}

void volvc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "volvc_cb");
    volbri.vs_value = lv_slider_get_value(ui_vslider);

    static char vs_buffer[10];
    lv_snprintf(vs_buffer, sizeof(vs_buffer), "%" PRId32, volbri.vs_value);
    lv_label_set_text(ui_bvbv, vs_buffer);
}

void volre_cb(lv_event_t *e)
{
    // write volume value into nvs and post event
    set_sound(UI_CALLER, volbri.vs_value);
}

void brivc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "brivc_cb");
    volbri.bs_value = lv_slider_get_value(ui_bslider);

    static char bs_buffer[10];
    lv_snprintf(bs_buffer, sizeof(bs_buffer), "%" PRId32, volbri.bs_value);
    lv_label_set_text(ui_bvbv, bs_buffer);
}

void brire_cb(lv_event_t *e)
{
    set_brightness(UI_CALLER, volbri.bs_value);
}

void hap_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "hap_cb");
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void slpt1c_cb(lv_event_t *e) { }

void slpt2c_cb(lv_event_t *e) { }

void slpt3c_cb(lv_event_t *e) { }

void slpt4c_cb(lv_event_t *e) { }

void slpt5c_cb(lv_event_t *e) { }

void slpt6c_cb(lv_event_t *e) { }

void slpt7c_cb(lv_event_t *e) { }
/* Page status bundle
 *
 */
static void Page_ConnAPP_Mate()
{
    lv_arc_set_value(ui_conn_arcr, 0);
    lv_obj_clear_flag(ui_conn_panel1, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_add_flag(ui_conn_panel2, LV_OBJ_FLAG_HIDDEN);   /// Flags
    lv_obj_clear_flag(ui_arrow1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_arrow2, LV_OBJ_FLAG_HIDDEN);

    static lv_color_t bg_color;
    bg_color = lv_palette_lighten(LV_PALETTE_LIGHT_BLUE, 5);
    static lv_color_t fg_color;
    fg_color = lv_palette_darken(LV_PALETTE_BLUE, 4);

    static lv_obj_t *qr;
    qr = lv_qrcode_create(ui_conn_QR, 150, fg_color, bg_color);
    static const char *data = "https://sensecap-mate-download.seeed.cc/";
    lv_qrcode_update(qr, data, strlen(data));
    lv_obj_center(qr);
}

static void Page_ConnAPP_BLE()
{
    lv_arc_set_value(ui_conn_arcr, 100);
    lv_obj_add_flag(ui_conn_panel1, LV_OBJ_FLAG_HIDDEN);   /// Flags
    lv_obj_clear_flag(ui_conn_panel2, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_add_flag(ui_arrow1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_arrow2, LV_OBJ_FLAG_HIDDEN);

    static lv_color_t bg_color;
    bg_color = lv_palette_lighten(LV_PALETTE_LIGHT_BLUE, 5);
    static lv_color_t fg_color;
    fg_color = lv_palette_darken(LV_PALETTE_BLUE, 4);

    static lv_obj_t *qr;
    qr = lv_qrcode_create(ui_conn_QR, 160, fg_color, bg_color);

    lv_qrcode_update(qr, sn_data, strlen(sn_data));
    lv_obj_center(qr);
}

static void Task_end()
{
    task_down = 1;
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_ALARM_OFF, &task_down, sizeof(uint8_t), portMAX_DELAY);
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_STOP, NULL, NULL, portMAX_DELAY);
    lv_obj_add_flag(ui_viewlivp, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_add_flag(ui_viewavap, LV_OBJ_FLAG_HIDDEN); /// Flags
    // event_post_to
    lv_pm_open_page(g_main, &group_page_template, PM_ADD_OBJS_TO_GROUP, &ui_Page_LocTask, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_LocTask_screen_init);
}

static void Page_shutdown()
{
    lv_label_set_text(ui_sptitle, "Shut down");
    if (shutdown_state == 1)
    {
        lv_label_set_text(ui_sptext, "Swipe to shut down");
    }
    else if (shutdown_state == 0)
    {
        lv_label_set_text(ui_sptext, "Swipe to reboot");
    }
}

static void Page_facreset()
{
    lv_label_set_text(ui_sptitle, "Factory reset");
    lv_label_set_text(ui_sptext, "Swipe to reset");
}

// device bind config status
void waitForWifi()
{
    lv_obj_add_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifip2, LV_OBJ_FLAG_HIDDEN);
    lv_img_set_src(ui_wifilogo, &ui_img_wifi_3_png);
    lv_obj_clear_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifitext2, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_wifitext3, "Waiting for Wi-Fi Setup...");
}

void waitForBinding()
{
    lv_obj_add_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifip2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_wifitext2, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_wifitext3, "Waiting for binding...");
}

void waitForAddDev()
{
    lv_obj_add_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifip2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_wifitext2, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_wifitext3, "Binding device to your account");
}

void bindFinish()
{
    lv_obj_add_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifip2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifitext2, LV_OBJ_FLAG_HIDDEN);
    lv_img_set_src(ui_wifilogo, &ui_img_wifiok_png);
    lv_obj_clear_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_wifitext3, "Watcher is ready");
}

void wifiConnectFailed()
{
    lv_obj_add_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifip2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifitext2, LV_OBJ_FLAG_HIDDEN);
    lv_img_set_src(ui_wifilogo, &ui_img_error_png);
    lv_obj_clear_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_wifitext3, "Wi-Fi Connection Failed");
}

static void settingInfoInit()
{
    lv_slider_set_range(ui_bslider, 1, 100);
    lv_obj_add_state(ui_setblesw, LV_STATE_CHECKED);
    get_sn(UI_CALLER);
    get_brightness(UI_CALLER);
    get_rgb_switch(UI_CALLER);
    get_sound(UI_CALLER);

    // Update SN、EUI、BT-MAC to about device page
    static char about_sn[20];
    static char about_eui[40];
    static char about_btmac[20];
    static char about_sw_version[20];

    const uint8_t *sn_code = get_sn_code();
    const uint8_t *eui_code = get_eui();
    const uint8_t *bt_mac = get_bt_mac();
    const char *sw_version = get_software_version(UI_CALLER);

    snprintf(about_sn, sizeof(about_sn), "%02X%02X%02X%02X%02X%02X%02X%02X%02X", sn_code[0], sn_code[1], sn_code[2], sn_code[3], sn_code[4], sn_code[5], sn_code[6], sn_code[7], sn_code[8]);

    snprintf(about_eui, sizeof(about_eui), "%02X%02X%02X%02X%02X%02X%02X%02X", eui_code[0], eui_code[1], eui_code[2], eui_code[3], eui_code[4], eui_code[5], eui_code[6], eui_code[7]);

    snprintf(about_btmac, sizeof(about_btmac), "%02X:%02X:%02X:%02X:%02X:%02X", bt_mac[0], bt_mac[1], bt_mac[2], bt_mac[3], bt_mac[4], bt_mac[5]);

    snprintf(about_sw_version, sizeof(about_sw_version), "%s", sw_version);

    lv_label_set_text(ui_svt2, about_sw_version);
    lv_label_set_text(ui_snt2, (char *)about_sn);
    lv_label_set_text(ui_euit2, (char *)about_eui);
    lv_label_set_text(ui_blet2, (char *)about_btmac);
}