// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ai

#include "../ui.h"

void ui_Page_Start_screen_init(void)
{
    ui_Page_Start = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Start, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startlogo = lv_img_create(ui_Page_Start);
    lv_img_set_src(ui_startlogo, &ui_img_logo_png);
    lv_obj_set_width(ui_startlogo, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_startlogo, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_align(ui_startlogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startlogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_startlogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Page_Start, ui_event_Page_Start, LV_EVENT_ALL, NULL);

}
