// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ai

#include "../ui.h"

void ui_Page_ViewAva_screen_init(void)
{
    ui_Page_ViewAva = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_ViewAva, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_ViewAva, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_ViewAva, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_viewavap2 = lv_obj_create(ui_Page_ViewAva);
    lv_obj_set_width(ui_viewavap2, 412);
    lv_obj_set_height(ui_viewavap2, 412);
    lv_obj_set_align(ui_viewavap2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_viewavap2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_viewavap2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_viewavap2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_viewavap2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_viewavap2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_viewavap2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_guideimg1 = lv_img_create(ui_viewavap2);
    lv_img_set_src(ui_guideimg1, &ui_img_scroll_down_png);
    lv_obj_set_width(ui_guideimg1, LV_SIZE_CONTENT);   /// 222
    lv_obj_set_height(ui_guideimg1, LV_SIZE_CONTENT);    /// 234
    lv_obj_set_x(ui_guideimg1, 43);
    lv_obj_set_y(ui_guideimg1, -33);
    lv_obj_set_align(ui_guideimg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_guideimg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_guideimg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_viewavap2, ui_event_viewavap2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page_ViewAva, ui_event_Page_ViewAva, LV_EVENT_ALL, NULL);

}
