// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_Sleep_screen_init(void)
{
    ui_Page_Sleep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Sleep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Sleep, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Sleep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sleeptimeroller = lv_roller_create(ui_Page_Sleep);
    lv_roller_set_options(ui_sleeptimeroller, "Never\n1 min\n5 min\n10 min\n15 min\n30 min\n24 hours",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_sleeptimeroller, 250);
    lv_obj_set_height(ui_sleeptimeroller, 153);
    lv_obj_set_x(ui_sleeptimeroller, 0);
    lv_obj_set_y(ui_sleeptimeroller, -40);
    lv_obj_set_align(ui_sleeptimeroller, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_sleeptimeroller, LV_STATE_FOCUSED);       /// States
    lv_obj_set_style_text_align(ui_sleeptimeroller, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sleeptimeroller, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sleeptimeroller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sleeptimeroller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sleeptimeroller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sleeptimeroller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_sleeptimeroller, lv_color_hex(0x2D89EF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_sleeptimeroller, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_sleeptimeroller, 4, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_sleeptimeroller, 15, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_bg_color(ui_sleeptimeroller, lv_color_hex(0x8FC31F), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sleeptimeroller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_sleeptimeroller, lv_color_hex(0x8FC31F), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_sleeptimeroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_sleeptimeroller, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_sleeptimeroller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_slpback = lv_btn_create(ui_Page_Sleep);
    lv_obj_set_width(ui_slpback, 60);
    lv_obj_set_height(ui_slpback, 60);
    lv_obj_set_x(ui_slpback, 0);
    lv_obj_set_y(ui_slpback, 120);
    lv_obj_set_align(ui_slpback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_slpback, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_slpback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_slpback, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slpback, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slpback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slpback, &ui_img_button_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_slpback, lv_color_hex(0x2D89EF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_slpback, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_slpback, 4, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_slpback, 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_add_event_cb(ui_sleeptimeroller, ui_event_sleeptimeroller, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_slpback, ui_event_slpback, LV_EVENT_ALL, NULL);

}
