// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai

#include "../ui.h"

void ui_Page_STime_screen_init(void)
{
    ui_Page_STime = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_STime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_STime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_STime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settimet = lv_obj_create(ui_Page_STime);
    lv_obj_set_width(ui_settimet, 288);
    lv_obj_set_height(ui_settimet, 60);
    lv_obj_set_x(ui_settimet, 0);
    lv_obj_set_y(ui_settimet, -179);
    lv_obj_set_align(ui_settimet, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settimet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settimet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settimet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_settimet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_settimet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timet = lv_label_create(ui_settimet);
    lv_obj_set_width(ui_timet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timet, "Time");
    lv_obj_set_style_text_color(ui_timet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timet, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Page_STime);
    lv_obj_set_width(ui_Button3, 200);
    lv_obj_set_height(ui_Button3, 60);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, 100);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Set Time");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_Page_STime);
    lv_roller_set_options(ui_Roller1,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Roller1, 75);
    lv_obj_set_height(ui_Roller1, 155);
    lv_obj_set_x(ui_Roller1, -70);
    lv_obj_set_y(ui_Roller1, -50);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Roller1, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller1, lv_color_hex(0xA3D936), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x91BF25), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 100, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Roller2 = lv_roller_create(ui_Page_STime);
    lv_roller_set_options(ui_Roller2,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Roller2, 70);
    lv_obj_set_height(ui_Roller2, 155);
    lv_obj_set_x(ui_Roller2, 70);
    lv_obj_set_y(ui_Roller2, -50);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Roller2, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller2, lv_color_hex(0xA3D936), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Roller2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x91BF25), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 100, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller2, lv_color_hex(0xA3D936), LV_PART_SELECTED | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Roller2, 255, LV_PART_SELECTED | LV_STATE_FOCUSED);

    ui_Label3 = lv_label_create(ui_Page_STime);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 2);
    lv_obj_set_y(ui_Label3, -48);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, ":");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_fontbold26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settimep = lv_obj_create(ui_Page_STime);
    lv_obj_set_width(ui_settimep, 348);
    lv_obj_set_height(ui_settimep, 356);
    lv_obj_set_x(ui_settimep, 0);
    lv_obj_set_y(ui_settimep, 24);
    lv_obj_set_align(ui_settimep, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_settimep, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_settimep, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_settimep, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scroll_dir(ui_settimep, LV_DIR_VER);
    lv_obj_set_style_radius(ui_settimep, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settimep, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settimep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_settimep, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_settimep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_settimep, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settimep, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_settimep, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_settimep, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_settimep, 60, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_settimep, 100, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_timep1 = lv_obj_create(ui_settimep);
    lv_obj_set_width(ui_timep1, 300);
    lv_obj_set_height(ui_timep1, 80);
    lv_obj_set_align(ui_timep1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timep1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_timep1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timep1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timep1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timep1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timep1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timet1 = lv_label_create(ui_timep1);
    lv_obj_set_width(ui_timet1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timet1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timet1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_timet1, "Automatic");
    lv_obj_set_style_text_color(ui_timet1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timet1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timet1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timesw = lv_switch_create(ui_timep1);
    lv_obj_set_width(ui_timesw, 80);
    lv_obj_set_height(ui_timesw, 35);
    lv_obj_set_x(ui_timesw, 80);
    lv_obj_set_y(ui_timesw, 0);
    lv_obj_set_align(ui_timesw, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_timesw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timesw, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_timesw, lv_color_hex(0x8FC31F), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_timesw, 50, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_timesw, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timesw, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_timesw, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_timesw, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_timesw, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_timesw, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_timesw, lv_color_hex(0x8FC31F), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_timesw, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_timep2 = lv_obj_create(ui_settimep);
    lv_obj_set_width(ui_timep2, 300);
    lv_obj_set_height(ui_timep2, 80);
    lv_obj_set_align(ui_timep2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timep2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_timep2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timep2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timep2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timep2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timep2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timet2 = lv_label_create(ui_timep2);
    lv_obj_set_width(ui_timet2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timet2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timet2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_timet2, "Manually Select");
    lv_obj_set_style_text_color(ui_timet2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timet2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timet2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timebtn = lv_btn_create(ui_timep2);
    lv_obj_set_width(ui_timebtn, 20);
    lv_obj_set_height(ui_timebtn, 20);
    lv_obj_set_x(ui_timebtn, 120);
    lv_obj_set_y(ui_timebtn, 0);
    lv_obj_set_align(ui_timebtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_timebtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timebtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timebtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_timebtn, &ui_img_left_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_timebtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_timebtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stimeb = lv_btn_create(ui_settimep);
    lv_obj_set_width(ui_stimeb, 60);
    lv_obj_set_height(ui_stimeb, 60);
    lv_obj_set_align(ui_stimeb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stimeb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_stimeb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_stimeb, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_stimeb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stimeb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_stimeb, &ui_img_button_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeselect = lv_obj_create(ui_Page_STime);
    lv_obj_set_width(ui_timeselect, 412);
    lv_obj_set_height(ui_timeselect, 412);
    lv_obj_set_align(ui_timeselect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeselect, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_timeselect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timeselect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeselect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timeselect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timeselect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timep2, ui_event_timep2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stimeb, ui_event_stimeb, LV_EVENT_ALL, NULL);

}
