// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: indoor_combo

#include "../ui.h"

void ui_screen_shutdown_screen_init(void)
{
ui_screen_shutdown = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_shutdown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_shutdown = lv_img_create(ui_screen_shutdown);
lv_img_set_src(ui_shutdown, &ui_img_shutdown_png);
lv_obj_set_width( ui_shutdown, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_shutdown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_shutdown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_shutdown, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_shutdown, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_shutdown, ui_event_shutdown, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screen_shutdown, ui_event_screen_shutdown, LV_EVENT_ALL, NULL);

}
