// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: indoor_combo

#include "../ui.h"

void ui_ui_shutdown_confirm_screen_init(void)
{
ui_ui_shutdown_confirm = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ui_shutdown_confirm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image8 = lv_img_create(ui_ui_shutdown_confirm);
lv_img_set_src(ui_Image8, &ui_img_ui_img__cancel_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image8, -40 );
lv_obj_set_y( ui_Image8, 40 );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_confirm = lv_img_create(ui_ui_shutdown_confirm);
lv_img_set_src(ui_confirm, &ui_img_ui_img_confirm_red_png);
lv_obj_set_width( ui_confirm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_confirm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_confirm, 40 );
lv_obj_set_y( ui_confirm, 40 );
lv_obj_set_align( ui_confirm, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_confirm, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_confirm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_ui_shutdown_confirm);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 0 );
lv_obj_set_y( ui_Label1, -20 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Do you want to turn off \n          the device?");

}
