// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: indoor_combo

#include "../ui.h"

void ui_ui_preview_screen_init(void)
{
ui_ui_preview = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ui_preview, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc2 = lv_arc_create(ui_ui_preview);
lv_obj_set_width( ui_Arc2, 240);
lv_obj_set_height( ui_Arc2, 240);
lv_obj_set_x( ui_Arc2, -1 );
lv_obj_set_y( ui_Arc2, 0 );
lv_obj_set_align( ui_Arc2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Arc2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_Arc2, LV_SCROLLBAR_MODE_OFF);
lv_arc_set_value(ui_Arc2, 360);
lv_arc_set_bg_angles(ui_Arc2,0,360);

lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xFF4040), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Arc2, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFF0008), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Arc2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

}
