// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai

#include "ui.h"
#include "esp_log.h"
#include "pm.h"
#include "animation.h"
#include "data_defs.h"
#include "event_loops.h"
#include "app_device_info.h"
#include "app_ble.h"
#include "lv_examples.h"

static const char * TAG = "ui_event:";

static void Page_ConnAPP_BLE();
static void Page_ConnAPP_Mate();
static void Task_end();
static void Page_shutdown();
static void Page_facreset();

static void set_obj_style_defocused(lv_obj_t * obj, lv_obj_t * obj_text)
{
	lv_obj_set_width(obj, 412);
    lv_obj_set_height(obj, 50);
    lv_obj_set_style_radius(obj, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(obj, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(obj_text, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void set_obj_style_focused(lv_obj_t * obj, lv_obj_t * obj_text)
{
	lv_obj_set_width(obj, 380);
    lv_obj_set_height(obj, 90);
    lv_obj_set_style_radius(obj, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(obj, lv_color_hex(0xA9DE2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(obj, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(obj_text, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void startload_cb(lv_event_t * e)
{
	_ui_screen_change(&ui_Page_Vir, LV_SCR_LOAD_ANIM_FADE_ON, 100, 3000, &ui_Page_Vir_screen_init);
}

void virtualp_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, ui_Page_main_group, 4, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void main1c_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, ui_Page_template_group, 7, PM_ADD_OBJS_TO_GROUP, &ui_Page_LocTask, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_LocTask_screen_init);
	lv_group_focus_obj(ui_Page_template_group[3]);
}

void main1f_cb(lv_event_t * e)
{
	lv_obj_set_y(ui_maintitle, 0);
	lv_label_set_text(ui_maintitle, "Task\nTemplates");
}

void main2c_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, NULL, NULL, PM_CLEAR_GROUP, &ui_Page_CurTask1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_CurTask1_screen_init);
}

void main2f_cb(lv_event_t * e)
{
	lv_obj_set_y(ui_maintitle, 0);
	lv_label_set_text(ui_maintitle, "Current\nTasks");
}

void main3c_cb(lv_event_t * e)
{
	esp_event_post_to(view_event_handle, VIEW_EVENT_BASE, VIEW_EVENT_ALARM_ON, NULL, 0, portMAX_DELAY);
	// lv_pm_open_page(g_main, group_ha, 1, PM_ADD_OBJS_TO_GROUP, &ui_Page_HA, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_HA_screen_init);
}

void main3f_cb(lv_event_t * e)
{
	lv_obj_set_y(ui_maintitle, 20);
	lv_label_set_text(ui_maintitle, "Extension");
}

void main4c_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, ui_Page_set_group, 12, PM_ADD_OBJS_TO_GROUP, &ui_Page_Set, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Set_screen_init);
}

void main4f_cb(lv_event_t * e)
{
	lv_obj_set_y(ui_maintitle, 20);
	lv_label_set_text(ui_maintitle, "Setting");
}

void connc_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, ui_Page_set_group, 12, PM_ADD_OBJS_TO_GROUP, &ui_Page_Set, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Set_screen_init);
}

void arr1c_cb(lv_event_t * e)
{
	Page_ConnAPP_BLE();
}

void arr2c_cb(lv_event_t * e)
{
	Page_ConnAPP_Mate();
}

void wifichange_cb(lv_event_t * e)
{
	
}

void nwific_cb(lv_event_t * e)
{

}

void ntaskb1c_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, NULL, NULL, PM_CLEAR_GROUP, &ui_Page_CurTask2, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_CurTask2_screen_init);
}

void ntaskb2c_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, ui_Page_main_group, 4, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void waitbc_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, ui_Page_main_group, 4, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void revbc_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, ui_Page_main_group, 4, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void viewac_cb(lv_event_t * e)
{
	lv_obj_clear_flag(ui_viewavap, LV_OBJ_FLAG_HIDDEN);     /// Flags
}

void viewaf_cb(lv_event_t * e)
{
	lv_pm_open_page(NULL, NULL, 0, PM_NO_OPERATION, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_ViewAva_screen_init);
	// ESP_LOGI(TAG, "view_ava_focused");
}

void ava1c_cb(lv_event_t * e)
{
	Task_end();
}

void ava2c_cb(lv_event_t * e)
{
	lv_obj_add_flag(ui_viewavap, LV_OBJ_FLAG_HIDDEN);     /// Flags
}

void viewlc_cb(lv_event_t * e)
{
	lv_obj_clear_flag(ui_viewlivp, LV_OBJ_FLAG_HIDDEN);     /// Flags
}

void viewlf_cb(lv_event_t * e)
{
	lv_pm_open_page(NULL, NULL, 0, PM_NO_OPERATION, &ui_Page_ViewLive, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_ViewLive_screen_init);
	// ESP_LOGI(TAG, "view_live_focused");
}

void liv1c_cb(lv_event_t * e)
{
	Task_end();
}

void liv2c_cb(lv_event_t * e)
{
	lv_obj_add_flag(ui_viewlivp, LV_OBJ_FLAG_HIDDEN);     /// Flags
}

void waitT_cb(lv_event_t * e)
{
	// Your code here
}

void loctask1c_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, ui_Page_main_group, 4, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void loctask1f_cb(lv_event_t * e)
{
	lv_obj_add_flag(ui_mimgp, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_mtext, LV_OBJ_FLAG_HIDDEN);
}

void loctask1df_cb(lv_event_t * e)
{
	lv_obj_clear_flag(ui_mimgp, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_mtext, LV_OBJ_FLAG_HIDDEN);
}

void loctask2c_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, group_view, 2, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_ViewAva_screen_init);
}

void loctask2f_cb(lv_event_t * e)
{
	lv_label_set_text(ui_Label1, "Human\nDetection");
	lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_human_d_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void loctask3c_cb(lv_event_t * e)
{

}

void loctask3f_cb(lv_event_t * e)
{
	lv_label_set_text(ui_Label1, "Gesture\nDetection");
	lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_gesture_d_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void loctask4c_cb(lv_event_t * e)
{

}

void loctask4f_cb(lv_event_t * e)
{
	lv_label_set_text(ui_Label1, "Pet\nDetection");
	lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_dog_d_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void locavac_cb(lv_event_t * e)
{

}

void loclivc_cb(lv_event_t * e)
{
	
}

void sgesup_cb(lv_event_t * e)
{
	lv_group_focus_next(g_main);
}

void sgesdown_cb(lv_event_t * e)
{
	lv_group_focus_prev(g_main);
}

void sclick_cb(lv_event_t * e)
{
	lv_obj_t * focused_obj = lv_group_get_focused(g_main);
	lv_event_send(focused_obj, LV_EVENT_CLICKED, NULL);
}

void mgesup_cb(lv_event_t * e)
{
	lv_group_focus_next(g_main);
}

void mgesdown_cb(lv_event_t * e)
{
	lv_group_focus_prev(g_main);
}

void lgesleft_cb(lv_event_t * e)
{
	lv_group_focus_next(g_main);
}

void lgesright_cb(lv_event_t * e)
{
	lv_group_focus_prev(g_main);
}

void mclick_cb(lv_event_t * e)
{
	lv_obj_t * focused_obj = lv_group_get_focused(g_main);
	lv_event_send(focused_obj, LV_EVENT_CLICKED, NULL);
}

void lclick_cb(lv_event_t * e)
{
	lv_obj_t * focused_obj = lv_group_get_focused(g_main);
	lv_event_send(focused_obj, LV_EVENT_CLICKED, NULL);
}

void custb1c_cb(lv_event_t * e)
{

}

void custb1f_cb(lv_event_t * e)
{
	lv_label_set_text(ui_Label1, "Template\n1");
	lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_template_add_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void custb1df_cb(lv_event_t * e)
{

}

void custb2c_cb(lv_event_t * e)
{

}

void custb2f_cb(lv_event_t * e)
{
	lv_label_set_text(ui_Label1, "Template\n2");
	lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_template_add_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void custb2df_cb(lv_event_t * e)
{

}

void custb3c_cb(lv_event_t * e)
{

}

void custb3f_cb(lv_event_t * e)
{
	lv_label_set_text(ui_Label1, "Template\n3");
	lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_template_add_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void custb3df_cb(lv_event_t * e)
{

}

void setbackf_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_setback, ui_setbackt);
}

void setbackdf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_setback, ui_setbackt);
}

void setdevf_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_setdev, ui_setdevt);
}

void setdevdf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_setdev, ui_setdevt);
}

void setwifif_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_setwifi, ui_setwifit);
}

void setwifidf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_setwifi, ui_setwifit);
}

void setrgbf_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_setrgb, ui_setrgbt);
	lv_obj_clear_flag(ui_setrgbsw, LV_OBJ_FLAG_HIDDEN);
}

void setrgbdf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_setrgb, ui_setrgbt);
	lv_obj_add_flag(ui_setrgbsw, LV_OBJ_FLAG_HIDDEN);
}

void setdownf_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_setdown, ui_setdownt);
}

void setdowndf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_setdown, ui_setdownt);
}

void setblef_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_setble, ui_setblet);
	lv_obj_clear_flag(ui_setblesw, LV_OBJ_FLAG_HIDDEN);

}

void setbledf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_setble, ui_setblet);
	lv_obj_add_flag(ui_setblesw, LV_OBJ_FLAG_HIDDEN);
}

void setvolc_cb(lv_event_t * e)
{
	lv_label_set_text(ui_bvtitle, "Sound");
	lv_label_set_text(ui_bvbt, "Volume");
	lv_obj_add_flag(ui_bp, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_vp, LV_OBJ_FLAG_HIDDEN);
	lv_pm_open_page(g_main, NULL, NULL, PM_CLEAR_GROUP, &ui_Page_brivol, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_brivol_screen_init);
	lv_event_send(ui_vslider, LV_EVENT_VALUE_CHANGED, NULL);
}

void setvolf_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_setvol, ui_setvolt);
}

void setvoldf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_setvol, ui_setvolt);
}

void setbric_cb(lv_event_t * e)
{
	lv_label_set_text(ui_bvtitle, "Display");
	lv_label_set_text(ui_bvbt, "Brightness");
	lv_obj_clear_flag(ui_bp, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_vp, LV_OBJ_FLAG_HIDDEN);
	lv_pm_open_page(g_main, NULL, NULL, PM_CLEAR_GROUP, &ui_Page_brivol, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_brivol_screen_init);
	lv_event_send(ui_bslider, LV_EVENT_VALUE_CHANGED, NULL);
}

void setbrif_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_setbri, ui_setbrit);
}

void setbridf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_setbri, ui_setbrit);
}

void setwwf_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_setww, ui_setwwt);
	lv_obj_clear_flag(ui_setwwsw, LV_OBJ_FLAG_HIDDEN);
}

void setwwdf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_setww, ui_setwwt);
	lv_obj_add_flag(ui_setwwsw, LV_OBJ_FLAG_HIDDEN);
}

void settimec_cb(lv_event_t * e)
{
	lv_obj_clear_flag(ui_settimep, LV_OBJ_FLAG_HIDDEN);
	lv_pm_open_page(g_main, NULL, NULL, PM_CLEAR_GROUP, &ui_Page_STime, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_STime);
}

void settimef_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_settime, ui_settimt);
}

void settimedf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_settime, ui_settimt);
}

void setfacf_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_setfac, ui_setfact);
}

void setfacdf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_setfac, ui_setfact);
}

void abdnf_cb(lv_event_t * e)
{

}

void abdndf_cb(lv_event_t * e)
{

}

void absvf_cb(lv_event_t * e)
{

}

void absvdf_cb(lv_event_t * e)
{

}

void absnf_cb(lv_event_t * e)
{

}

void absndf_cb(lv_event_t * e)
{

}

void abeuif_cb(lv_event_t * e)
{

}

void abeuidf_cb(lv_event_t * e)
{

}

void abblef_cb(lv_event_t * e)
{

}

void abbledf_cb(lv_event_t * e)
{

}

void paboutc_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, ui_Page_set_group, 12, PM_ADD_OBJS_TO_GROUP, &ui_Page_Set, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Set_screen_init);
}

void setbackc_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, ui_Page_main_group, 4, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

void setdevc_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, NULL, NULL, PM_CLEAR_GROUP, &ui_Page_SAbout, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_SAbout_screen_init);
}

void setwific_cb(lv_event_t * e)
{
	//unbinded
	lv_pm_open_page(g_main, NULL, NULL, PM_CLEAR_GROUP, &ui_Page_Connect, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Connect_screen_init);
	Page_ConnAPP_Mate();

	//binded

}

void setblec_cb(lv_event_t * e)
{
	static lv_state_t btn_state;
	btn_state = lv_obj_get_state(ui_setblesw);
	switch (btn_state)
	{
	case 1:
		lv_obj_clear_state(ui_setblesw, LV_STATE_CHECKED);
		ESP_LOGI(TAG, "ble_btn_status: off");
		set_ble_status(0,2);
		break;
	case 0:
		lv_obj_add_state(ui_setblesw, LV_STATE_CHECKED);
		ESP_LOGI(TAG, "ble_btn_status: on");
		set_ble_status(0,1);
		break;
	
	default:
		break;
	}
}

void setrgbc_cb(lv_event_t * e)
{
	static lv_state_t btn_state;
	btn_state = lv_obj_get_state(ui_setrgbsw);
	switch (btn_state)
	{
	case 0:
		lv_obj_add_state(ui_setrgbsw, LV_STATE_CHECKED);
		break;
	case 1:
		lv_obj_clear_state(ui_setrgbsw, LV_STATE_CHECKED);
		break;
	
	default:
		break;
	}
}

void setwwc_cb(lv_event_t * e)
{
	static lv_state_t btn_state;
	btn_state = lv_obj_get_state(ui_setwwsw);
	switch (btn_state)
	{
	case 0:
		lv_obj_add_state(ui_setwwsw, LV_STATE_CHECKED);
		break;
	case 1:
		lv_obj_clear_state(ui_setwwsw, LV_STATE_CHECKED);
		break;
	
	default:
		break;
	}
}

void setdownc_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, NULL, NULL, PM_CLEAR_GROUP, &ui_Page_Swipe, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Swipe_screen_init);
	Page_shutdown();
}

void setfac_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, NULL, NULL, PM_CLEAR_GROUP, &ui_Page_Swipe, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Swipe_screen_init);
	Page_facreset();
}

void setappf_cb(lv_event_t * e)
{
	set_obj_style_focused(ui_setapp, ui_setappt);
}

void setappdf_cb(lv_event_t * e)
{
	set_obj_style_defocused(ui_setapp, ui_setappt);
}

void setappc_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, NULL, NULL, PM_CLEAR_GROUP, &ui_Page_Connect, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Connect_screen_init);
	Page_ConnAPP_Mate();
	get_sn(0);
}

void slidervc_cb(lv_event_t * e)
{
	int32_t slider_value =  lv_slider_get_value(ui_spsilder);
	// ESP_LOGI(TAG, "This is slider_value: %" PRId32, slider_value);
	if(slider_value>80)
	{
		lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xFF5656), LV_PART_MAIN | LV_STATE_DEFAULT);
		lv_obj_set_style_shadow_color(ui_spsilder, lv_color_hex(0xFF5656), LV_PART_MAIN | LV_STATE_DEFAULT);
		lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xFF5656), LV_PART_INDICATOR | LV_STATE_DEFAULT);
	}
	else{
		lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_MAIN | LV_STATE_DEFAULT);
		lv_obj_set_style_shadow_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_MAIN | LV_STATE_DEFAULT);
		lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
	}
}

void sliderr_cb(lv_event_t * e)
{
	int32_t slider_value =  lv_slider_get_value(ui_spsilder);
	if(slider_value>80)
	{
		lv_pm_open_page(g_main, ui_Page_main_group, 4, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Page_main_screen_init);
	}
	lv_slider_set_value(ui_spsilder, 0, LV_ANIM_ON);
	lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
}

void stbtn_cb(lv_event_t * e)
{
	lv_obj_clear_flag(ui_settimep, LV_OBJ_FLAG_HIDDEN);
	lv_pm_open_page(g_main, NULL, NULL, PM_CLEAR_GROUP, &ui_Page_STime, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Set_screen_init);
}

void preset_cb(lv_event_t * e)
{

	lv_pm_open_page(g_main, ui_Page_set_group, 12, PM_ADD_OBJS_TO_GROUP, &ui_Page_Set, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_Set_screen_init);
}

void timebtn_cb(lv_event_t * e)
{

}

void timesc_cb(lv_event_t * e)
{
	lv_obj_add_flag(ui_settimep, LV_OBJ_FLAG_HIDDEN);
	lv_group_add_obj(g_main, ui_Roller1);
	lv_group_add_obj(g_main, ui_Roller2);
}

void volvc_cb(lv_event_t * e)
{
	static int32_t vs_value;
	vs_value =  lv_slider_get_value(ui_vslider);

	char vs_buffer[10];
	lv_snprintf(vs_buffer, sizeof(vs_buffer), "%" PRId32, vs_value);
    lv_label_set_text(ui_bvbv, vs_buffer);
}

void volre_cb(lv_event_t * e)
{

}

void brivc_cb(lv_event_t * e)
{
	static int32_t bs_value;
	bs_value =  lv_slider_get_value(ui_bslider);

	char bs_buffer[10];
	lv_snprintf(bs_buffer, sizeof(bs_buffer), "%" PRId32, bs_value);
    lv_label_set_text(ui_bvbv, bs_buffer); 
}

void brire_cb(lv_event_t * e)
{

}

void hap_cb(lv_event_t * e)
{
	lv_pm_open_page(g_main, ui_Page_main_group, 4, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

// Page status bundle
static void Page_ConnAPP_Mate()
{
	lv_arc_set_value(ui_conn_arcr, 0);
	lv_obj_clear_flag(ui_conn_panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
	lv_obj_add_flag(ui_conn_panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
	lv_obj_clear_flag(ui_arrow1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_arrow2, LV_OBJ_FLAG_HIDDEN);

	lv_color_t bg_color = lv_palette_lighten(LV_PALETTE_LIGHT_BLUE, 5);
    lv_color_t fg_color = lv_palette_darken(LV_PALETTE_BLUE, 4);

	lv_obj_t * qr = lv_qrcode_create(ui_conn_QR, 150, fg_color, bg_color);
	const char * data = "https://sensecap-mate-download.seeed.cc/";
    lv_qrcode_update(qr, data, strlen(data));
    lv_obj_center(qr);



}

static void Page_ConnAPP_BLE()
{
	lv_arc_set_value(ui_conn_arcr, 100);
	lv_obj_add_flag(ui_conn_panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
	lv_obj_clear_flag(ui_conn_panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
	lv_obj_add_flag(ui_arrow1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_arrow2, LV_OBJ_FLAG_HIDDEN);

	lv_color_t bg_color = lv_palette_lighten(LV_PALETTE_LIGHT_BLUE, 5);
    lv_color_t fg_color = lv_palette_darken(LV_PALETTE_BLUE, 4);

	lv_obj_t * qr = lv_qrcode_create(ui_conn_QR, 160, fg_color, bg_color);

    lv_qrcode_update(qr, sn_data, strlen(sn_data));
    lv_obj_center(qr);
}

static void Task_end()
{
	lv_obj_add_flag(ui_viewlivp, LV_OBJ_FLAG_HIDDEN);     /// Flags
	lv_obj_add_flag(ui_viewavap, LV_OBJ_FLAG_HIDDEN);     /// Flags
	// event_post_to 

	lv_pm_open_page(g_main, ui_Page_main_group, 4, PM_ADD_OBJS_TO_GROUP, &ui_Page_main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Page_main_screen_init);
}

static void Page_shutdown()
{
	lv_label_set_text(ui_sptitle, "Shut down");
	lv_label_set_text(ui_sptext, "Swipe to shut down");
}

static void Page_facreset()
{
	lv_label_set_text(ui_sptitle, "Factory reset");
	lv_label_set_text(ui_sptext, "Swipe to reset");
}